/*
Copyright 2022 The Katalyst Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/kubewharf/katalyst-api/pkg/apis/node/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeNodeProfileDescriptors implements NodeProfileDescriptorInterface
type FakeNodeProfileDescriptors struct {
	Fake *FakeNodeV1alpha1
}

var nodeprofiledescriptorsResource = schema.GroupVersionResource{Group: "node.katalyst.kubewharf.io", Version: "v1alpha1", Resource: "nodeprofiledescriptors"}

var nodeprofiledescriptorsKind = schema.GroupVersionKind{Group: "node.katalyst.kubewharf.io", Version: "v1alpha1", Kind: "NodeProfileDescriptor"}

// Get takes name of the nodeProfileDescriptor, and returns the corresponding nodeProfileDescriptor object, and an error if there is any.
func (c *FakeNodeProfileDescriptors) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.NodeProfileDescriptor, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(nodeprofiledescriptorsResource, name), &v1alpha1.NodeProfileDescriptor{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NodeProfileDescriptor), err
}

// List takes label and field selectors, and returns the list of NodeProfileDescriptors that match those selectors.
func (c *FakeNodeProfileDescriptors) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.NodeProfileDescriptorList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(nodeprofiledescriptorsResource, nodeprofiledescriptorsKind, opts), &v1alpha1.NodeProfileDescriptorList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.NodeProfileDescriptorList{ListMeta: obj.(*v1alpha1.NodeProfileDescriptorList).ListMeta}
	for _, item := range obj.(*v1alpha1.NodeProfileDescriptorList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested nodeProfileDescriptors.
func (c *FakeNodeProfileDescriptors) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(nodeprofiledescriptorsResource, opts))
}

// Create takes the representation of a nodeProfileDescriptor and creates it.  Returns the server's representation of the nodeProfileDescriptor, and an error, if there is any.
func (c *FakeNodeProfileDescriptors) Create(ctx context.Context, nodeProfileDescriptor *v1alpha1.NodeProfileDescriptor, opts v1.CreateOptions) (result *v1alpha1.NodeProfileDescriptor, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(nodeprofiledescriptorsResource, nodeProfileDescriptor), &v1alpha1.NodeProfileDescriptor{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NodeProfileDescriptor), err
}

// Update takes the representation of a nodeProfileDescriptor and updates it. Returns the server's representation of the nodeProfileDescriptor, and an error, if there is any.
func (c *FakeNodeProfileDescriptors) Update(ctx context.Context, nodeProfileDescriptor *v1alpha1.NodeProfileDescriptor, opts v1.UpdateOptions) (result *v1alpha1.NodeProfileDescriptor, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(nodeprofiledescriptorsResource, nodeProfileDescriptor), &v1alpha1.NodeProfileDescriptor{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NodeProfileDescriptor), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeNodeProfileDescriptors) UpdateStatus(ctx context.Context, nodeProfileDescriptor *v1alpha1.NodeProfileDescriptor, opts v1.UpdateOptions) (*v1alpha1.NodeProfileDescriptor, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(nodeprofiledescriptorsResource, "status", nodeProfileDescriptor), &v1alpha1.NodeProfileDescriptor{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NodeProfileDescriptor), err
}

// Delete takes name of the nodeProfileDescriptor and deletes it. Returns an error if one occurs.
func (c *FakeNodeProfileDescriptors) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(nodeprofiledescriptorsResource, name, opts), &v1alpha1.NodeProfileDescriptor{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeNodeProfileDescriptors) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(nodeprofiledescriptorsResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.NodeProfileDescriptorList{})
	return err
}

// Patch applies the patch and returns the patched nodeProfileDescriptor.
func (c *FakeNodeProfileDescriptors) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.NodeProfileDescriptor, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(nodeprofiledescriptorsResource, name, pt, data, subresources...), &v1alpha1.NodeProfileDescriptor{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NodeProfileDescriptor), err
}
