//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2022 The Katalyst Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	resource "k8s.io/apimachinery/pkg/api/resource"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	intstr "k8s.io/apimachinery/pkg/util/intstr"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessControlConfig) DeepCopyInto(out *AccessControlConfig) {
	*out = *in
	if in.AccessControlPolicies != nil {
		in, out := &in.AccessControlPolicies, &out.AccessControlPolicies
		*out = make([]AccessControlPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessControlConfig.
func (in *AccessControlConfig) DeepCopy() *AccessControlConfig {
	if in == nil {
		return nil
	}
	out := new(AccessControlConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessControlPolicy) DeepCopyInto(out *AccessControlPolicy) {
	*out = *in
	in.PolicyRule.DeepCopyInto(&out.PolicyRule)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessControlPolicy.
func (in *AccessControlPolicy) DeepCopy() *AccessControlPolicy {
	if in == nil {
		return nil
	}
	out := new(AccessControlPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdminQoSConfig) DeepCopyInto(out *AdminQoSConfig) {
	*out = *in
	if in.ReclaimedResourceConfig != nil {
		in, out := &in.ReclaimedResourceConfig, &out.ReclaimedResourceConfig
		*out = new(ReclaimedResourceConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.EvictionConfig != nil {
		in, out := &in.EvictionConfig, &out.EvictionConfig
		*out = new(EvictionConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.AdvisorConfig != nil {
		in, out := &in.AdvisorConfig, &out.AdvisorConfig
		*out = new(AdvisorConfig)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdminQoSConfig.
func (in *AdminQoSConfig) DeepCopy() *AdminQoSConfig {
	if in == nil {
		return nil
	}
	out := new(AdminQoSConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdminQoSConfiguration) DeepCopyInto(out *AdminQoSConfiguration) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdminQoSConfiguration.
func (in *AdminQoSConfiguration) DeepCopy() *AdminQoSConfiguration {
	if in == nil {
		return nil
	}
	out := new(AdminQoSConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AdminQoSConfiguration) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdminQoSConfigurationList) DeepCopyInto(out *AdminQoSConfigurationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AdminQoSConfiguration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdminQoSConfigurationList.
func (in *AdminQoSConfigurationList) DeepCopy() *AdminQoSConfigurationList {
	if in == nil {
		return nil
	}
	out := new(AdminQoSConfigurationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AdminQoSConfigurationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdminQoSConfigurationSpec) DeepCopyInto(out *AdminQoSConfigurationSpec) {
	*out = *in
	in.GenericConfigSpec.DeepCopyInto(&out.GenericConfigSpec)
	in.Config.DeepCopyInto(&out.Config)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdminQoSConfigurationSpec.
func (in *AdminQoSConfigurationSpec) DeepCopy() *AdminQoSConfigurationSpec {
	if in == nil {
		return nil
	}
	out := new(AdminQoSConfigurationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdvisorConfig) DeepCopyInto(out *AdvisorConfig) {
	*out = *in
	if in.CPUAdvisorConfig != nil {
		in, out := &in.CPUAdvisorConfig, &out.CPUAdvisorConfig
		*out = new(CPUAdvisorConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.MemoryAdvisorConfig != nil {
		in, out := &in.MemoryAdvisorConfig, &out.MemoryAdvisorConfig
		*out = new(MemoryAdvisorConfig)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdvisorConfig.
func (in *AdvisorConfig) DeepCopy() *AdvisorConfig {
	if in == nil {
		return nil
	}
	out := new(AdvisorConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlgorithmConfig) DeepCopyInto(out *AlgorithmConfig) {
	*out = *in
	if in.Params != nil {
		in, out := &in.Params, &out.Params
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	out.TimeWindow = in.TimeWindow
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlgorithmConfig.
func (in *AlgorithmConfig) DeepCopy() *AlgorithmConfig {
	if in == nil {
		return nil
	}
	out := new(AlgorithmConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthConfig) DeepCopyInto(out *AuthConfig) {
	*out = *in
	if in.BasicAuthConfig != nil {
		in, out := &in.BasicAuthConfig, &out.BasicAuthConfig
		*out = new(BasicAuthConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.AccessControlConfig != nil {
		in, out := &in.AccessControlConfig, &out.AccessControlConfig
		*out = new(AccessControlConfig)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthConfig.
func (in *AuthConfig) DeepCopy() *AuthConfig {
	if in == nil {
		return nil
	}
	out := new(AuthConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthConfiguration) DeepCopyInto(out *AuthConfiguration) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthConfiguration.
func (in *AuthConfiguration) DeepCopy() *AuthConfiguration {
	if in == nil {
		return nil
	}
	out := new(AuthConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AuthConfiguration) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthConfigurationList) DeepCopyInto(out *AuthConfigurationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AuthConfiguration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthConfigurationList.
func (in *AuthConfigurationList) DeepCopy() *AuthConfigurationList {
	if in == nil {
		return nil
	}
	out := new(AuthConfigurationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AuthConfigurationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthConfigurationSpec) DeepCopyInto(out *AuthConfigurationSpec) {
	*out = *in
	in.GenericConfigSpec.DeepCopyInto(&out.GenericConfigSpec)
	in.Config.DeepCopyInto(&out.Config)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthConfigurationSpec.
func (in *AuthConfigurationSpec) DeepCopy() *AuthConfigurationSpec {
	if in == nil {
		return nil
	}
	out := new(AuthConfigurationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BasicAuthConfig) DeepCopyInto(out *BasicAuthConfig) {
	*out = *in
	if in.UserPasswordPairs != nil {
		in, out := &in.UserPasswordPairs, &out.UserPasswordPairs
		*out = make([]UserPasswordPair, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BasicAuthConfig.
func (in *BasicAuthConfig) DeepCopy() *BasicAuthConfig {
	if in == nil {
		return nil
	}
	out := new(BasicAuthConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlockConfig) DeepCopyInto(out *BlockConfig) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make([]v1.LabelSelectorRequirement, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make([]v1.LabelSelectorRequirement, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlockConfig.
func (in *BlockConfig) DeepCopy() *BlockConfig {
	if in == nil {
		return nil
	}
	out := new(BlockConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CPUAdvisorConfig) DeepCopyInto(out *CPUAdvisorConfig) {
	*out = *in
	if in.AllowSharedCoresOverlapReclaimedCores != nil {
		in, out := &in.AllowSharedCoresOverlapReclaimedCores, &out.AllowSharedCoresOverlapReclaimedCores
		*out = new(bool)
		**out = **in
	}
	if in.CPUProvisionConfig != nil {
		in, out := &in.CPUProvisionConfig, &out.CPUProvisionConfig
		*out = new(CPUProvisionConfig)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CPUAdvisorConfig.
func (in *CPUAdvisorConfig) DeepCopy() *CPUAdvisorConfig {
	if in == nil {
		return nil
	}
	out := new(CPUAdvisorConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CPUHeadroomConfig) DeepCopyInto(out *CPUHeadroomConfig) {
	*out = *in
	if in.UtilBasedConfig != nil {
		in, out := &in.UtilBasedConfig, &out.UtilBasedConfig
		*out = new(CPUHeadroomUtilBasedConfig)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CPUHeadroomConfig.
func (in *CPUHeadroomConfig) DeepCopy() *CPUHeadroomConfig {
	if in == nil {
		return nil
	}
	out := new(CPUHeadroomConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CPUHeadroomUtilBasedConfig) DeepCopyInto(out *CPUHeadroomUtilBasedConfig) {
	*out = *in
	if in.Enable != nil {
		in, out := &in.Enable, &out.Enable
		*out = new(bool)
		**out = **in
	}
	if in.TargetReclaimedCoreUtilization != nil {
		in, out := &in.TargetReclaimedCoreUtilization, &out.TargetReclaimedCoreUtilization
		*out = new(float64)
		**out = **in
	}
	if in.MaxReclaimedCoreUtilization != nil {
		in, out := &in.MaxReclaimedCoreUtilization, &out.MaxReclaimedCoreUtilization
		*out = new(float64)
		**out = **in
	}
	if in.MaxOversoldRate != nil {
		in, out := &in.MaxOversoldRate, &out.MaxOversoldRate
		*out = new(float64)
		**out = **in
	}
	if in.MaxHeadroomCapacityRate != nil {
		in, out := &in.MaxHeadroomCapacityRate, &out.MaxHeadroomCapacityRate
		*out = new(float64)
		**out = **in
	}
	if in.NonReclaimUtilizationHigh != nil {
		in, out := &in.NonReclaimUtilizationHigh, &out.NonReclaimUtilizationHigh
		*out = new(float64)
		**out = **in
	}
	if in.NonReclaimUtilizationLow != nil {
		in, out := &in.NonReclaimUtilizationLow, &out.NonReclaimUtilizationLow
		*out = new(float64)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CPUHeadroomUtilBasedConfig.
func (in *CPUHeadroomUtilBasedConfig) DeepCopy() *CPUHeadroomUtilBasedConfig {
	if in == nil {
		return nil
	}
	out := new(CPUHeadroomUtilBasedConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CPUPressureEvictionConfig) DeepCopyInto(out *CPUPressureEvictionConfig) {
	*out = *in
	if in.EnableLoadEviction != nil {
		in, out := &in.EnableLoadEviction, &out.EnableLoadEviction
		*out = new(bool)
		**out = **in
	}
	if in.LoadUpperBoundRatio != nil {
		in, out := &in.LoadUpperBoundRatio, &out.LoadUpperBoundRatio
		*out = new(float64)
		**out = **in
	}
	if in.LoadLowerBoundRatio != nil {
		in, out := &in.LoadLowerBoundRatio, &out.LoadLowerBoundRatio
		*out = new(float64)
		**out = **in
	}
	if in.LoadThresholdMetPercentage != nil {
		in, out := &in.LoadThresholdMetPercentage, &out.LoadThresholdMetPercentage
		*out = new(float64)
		**out = **in
	}
	if in.LoadMetricRingSize != nil {
		in, out := &in.LoadMetricRingSize, &out.LoadMetricRingSize
		*out = new(int)
		**out = **in
	}
	if in.LoadEvictionCoolDownTime != nil {
		in, out := &in.LoadEvictionCoolDownTime, &out.LoadEvictionCoolDownTime
		*out = new(v1.Duration)
		**out = **in
	}
	if in.EnableSuppressionEviction != nil {
		in, out := &in.EnableSuppressionEviction, &out.EnableSuppressionEviction
		*out = new(bool)
		**out = **in
	}
	if in.MaxSuppressionToleranceRate != nil {
		in, out := &in.MaxSuppressionToleranceRate, &out.MaxSuppressionToleranceRate
		*out = new(float64)
		**out = **in
	}
	if in.MinSuppressionToleranceDuration != nil {
		in, out := &in.MinSuppressionToleranceDuration, &out.MinSuppressionToleranceDuration
		*out = new(v1.Duration)
		**out = **in
	}
	if in.GracePeriod != nil {
		in, out := &in.GracePeriod, &out.GracePeriod
		*out = new(int64)
		**out = **in
	}
	in.NumaCPUPressureEvictionConfig.DeepCopyInto(&out.NumaCPUPressureEvictionConfig)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CPUPressureEvictionConfig.
func (in *CPUPressureEvictionConfig) DeepCopy() *CPUPressureEvictionConfig {
	if in == nil {
		return nil
	}
	out := new(CPUPressureEvictionConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CPUProvisionConfig) DeepCopyInto(out *CPUProvisionConfig) {
	*out = *in
	if in.RegionIndicators != nil {
		in, out := &in.RegionIndicators, &out.RegionIndicators
		*out = make([]RegionIndicators, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Constraints != nil {
		in, out := &in.Constraints, &out.Constraints
		*out = make([]ControlKnobConstraints, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CPUProvisionConfig.
func (in *CPUProvisionConfig) DeepCopy() *CPUProvisionConfig {
	if in == nil {
		return nil
	}
	out := new(CPUProvisionConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CPUSystemPressureEvictionConfig) DeepCopyInto(out *CPUSystemPressureEvictionConfig) {
	*out = *in
	if in.EnableCPUSystemPressureEviction != nil {
		in, out := &in.EnableCPUSystemPressureEviction, &out.EnableCPUSystemPressureEviction
		*out = new(bool)
		**out = **in
	}
	if in.LoadUpperBoundRatio != nil {
		in, out := &in.LoadUpperBoundRatio, &out.LoadUpperBoundRatio
		*out = new(float64)
		**out = **in
	}
	if in.LoadLowerBoundRatio != nil {
		in, out := &in.LoadLowerBoundRatio, &out.LoadLowerBoundRatio
		*out = new(float64)
		**out = **in
	}
	if in.UsageUpperBoundRatio != nil {
		in, out := &in.UsageUpperBoundRatio, &out.UsageUpperBoundRatio
		*out = new(float64)
		**out = **in
	}
	if in.UsageLowerBoundRatio != nil {
		in, out := &in.UsageLowerBoundRatio, &out.UsageLowerBoundRatio
		*out = new(float64)
		**out = **in
	}
	if in.ThresholdMetPercentage != nil {
		in, out := &in.ThresholdMetPercentage, &out.ThresholdMetPercentage
		*out = new(float64)
		**out = **in
	}
	if in.MetricRingSize != nil {
		in, out := &in.MetricRingSize, &out.MetricRingSize
		*out = new(int)
		**out = **in
	}
	if in.EvictionCoolDownTime != nil {
		in, out := &in.EvictionCoolDownTime, &out.EvictionCoolDownTime
		*out = new(v1.Duration)
		**out = **in
	}
	if in.EvictionRankingMetrics != nil {
		in, out := &in.EvictionRankingMetrics, &out.EvictionRankingMetrics
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.GracePeriod != nil {
		in, out := &in.GracePeriod, &out.GracePeriod
		*out = new(int64)
		**out = **in
	}
	if in.CheckCPUManager != nil {
		in, out := &in.CheckCPUManager, &out.CheckCPUManager
		*out = new(bool)
		**out = **in
	}
	if in.RankingLabels != nil {
		in, out := &in.RankingLabels, &out.RankingLabels
		*out = make(map[string][]string, len(*in))
		for key, val := range *in {
			var outVal []string
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = make([]string, len(*in))
				copy(*out, *in)
			}
			(*out)[key] = outVal
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CPUSystemPressureEvictionConfig.
func (in *CPUSystemPressureEvictionConfig) DeepCopy() *CPUSystemPressureEvictionConfig {
	if in == nil {
		return nil
	}
	out := new(CPUSystemPressureEvictionConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CgroupConfig) DeepCopyInto(out *CgroupConfig) {
	*out = *in
	in.ConfigDetail.DeepCopyInto(&out.ConfigDetail)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CgroupConfig.
func (in *CgroupConfig) DeepCopy() *CgroupConfig {
	if in == nil {
		return nil
	}
	out := new(CgroupConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigUpdateStrategy) DeepCopyInto(out *ConfigUpdateStrategy) {
	*out = *in
	if in.RollingUpdate != nil {
		in, out := &in.RollingUpdate, &out.RollingUpdate
		*out = new(RollingUpdateConfig)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigUpdateStrategy.
func (in *ConfigUpdateStrategy) DeepCopy() *ConfigUpdateStrategy {
	if in == nil {
		return nil
	}
	out := new(ConfigUpdateStrategy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControlKnobConstraints) DeepCopyInto(out *ControlKnobConstraints) {
	*out = *in
	in.RestrictConstraints.DeepCopyInto(&out.RestrictConstraints)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControlKnobConstraints.
func (in *ControlKnobConstraints) DeepCopy() *ControlKnobConstraints {
	if in == nil {
		return nil
	}
	out := new(ControlKnobConstraints)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomNodeConfig) DeepCopyInto(out *CustomNodeConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomNodeConfig.
func (in *CustomNodeConfig) DeepCopy() *CustomNodeConfig {
	if in == nil {
		return nil
	}
	out := new(CustomNodeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CustomNodeConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomNodeConfigList) DeepCopyInto(out *CustomNodeConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CustomNodeConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomNodeConfigList.
func (in *CustomNodeConfigList) DeepCopy() *CustomNodeConfigList {
	if in == nil {
		return nil
	}
	out := new(CustomNodeConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CustomNodeConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomNodeConfigSpec) DeepCopyInto(out *CustomNodeConfigSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomNodeConfigSpec.
func (in *CustomNodeConfigSpec) DeepCopy() *CustomNodeConfigSpec {
	if in == nil {
		return nil
	}
	out := new(CustomNodeConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomNodeConfigStatus) DeepCopyInto(out *CustomNodeConfigStatus) {
	*out = *in
	if in.KatalystCustomConfigList != nil {
		in, out := &in.KatalystCustomConfigList, &out.KatalystCustomConfigList
		*out = make([]TargetConfig, len(*in))
		copy(*out, *in)
	}
	if in.ServiceProfileConfigList != nil {
		in, out := &in.ServiceProfileConfigList, &out.ServiceProfileConfigList
		*out = make([]TargetConfig, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomNodeConfigStatus.
func (in *CustomNodeConfigStatus) DeepCopy() *CustomNodeConfigStatus {
	if in == nil {
		return nil
	}
	out := new(CustomNodeConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DisableIRQCoresExclusionThresholds) DeepCopyInto(out *DisableIRQCoresExclusionThresholds) {
	*out = *in
	if in.RxPPSThreshold != nil {
		in, out := &in.RxPPSThreshold, &out.RxPPSThreshold
		*out = new(uint64)
		**out = **in
	}
	if in.SuccessiveCount != nil {
		in, out := &in.SuccessiveCount, &out.SuccessiveCount
		*out = new(int)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DisableIRQCoresExclusionThresholds.
func (in *DisableIRQCoresExclusionThresholds) DeepCopy() *DisableIRQCoresExclusionThresholds {
	if in == nil {
		return nil
	}
	out := new(DisableIRQCoresExclusionThresholds)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnableIRQCoresExclusionThresholds) DeepCopyInto(out *EnableIRQCoresExclusionThresholds) {
	*out = *in
	if in.RxPPSThreshold != nil {
		in, out := &in.RxPPSThreshold, &out.RxPPSThreshold
		*out = new(uint64)
		**out = **in
	}
	if in.SuccessiveCount != nil {
		in, out := &in.SuccessiveCount, &out.SuccessiveCount
		*out = new(int)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnableIRQCoresExclusionThresholds.
func (in *EnableIRQCoresExclusionThresholds) DeepCopy() *EnableIRQCoresExclusionThresholds {
	if in == nil {
		return nil
	}
	out := new(EnableIRQCoresExclusionThresholds)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EphemeralSelector) DeepCopyInto(out *EphemeralSelector) {
	*out = *in
	if in.NodeNames != nil {
		in, out := &in.NodeNames, &out.NodeNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.LastDuration != nil {
		in, out := &in.LastDuration, &out.LastDuration
		*out = new(v1.Duration)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EphemeralSelector.
func (in *EphemeralSelector) DeepCopy() *EphemeralSelector {
	if in == nil {
		return nil
	}
	out := new(EphemeralSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EvictionConfig) DeepCopyInto(out *EvictionConfig) {
	*out = *in
	if in.DryRun != nil {
		in, out := &in.DryRun, &out.DryRun
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.CPUPressureEvictionConfig != nil {
		in, out := &in.CPUPressureEvictionConfig, &out.CPUPressureEvictionConfig
		*out = new(CPUPressureEvictionConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.SystemLoadPressureEvictionConfig != nil {
		in, out := &in.SystemLoadPressureEvictionConfig, &out.SystemLoadPressureEvictionConfig
		*out = new(SystemLoadPressureEvictionConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.CPUSystemPressureEvictionConfig != nil {
		in, out := &in.CPUSystemPressureEvictionConfig, &out.CPUSystemPressureEvictionConfig
		*out = new(CPUSystemPressureEvictionConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.MemoryPressureEvictionConfig != nil {
		in, out := &in.MemoryPressureEvictionConfig, &out.MemoryPressureEvictionConfig
		*out = new(MemoryPressureEvictionConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.RootfsPressureEvictionConfig != nil {
		in, out := &in.RootfsPressureEvictionConfig, &out.RootfsPressureEvictionConfig
		*out = new(RootfsPressureEvictionConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.ReclaimedResourcesEvictionConfig != nil {
		in, out := &in.ReclaimedResourcesEvictionConfig, &out.ReclaimedResourcesEvictionConfig
		*out = new(ReclaimedResourcesEvictionConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.NetworkEvictionConfig != nil {
		in, out := &in.NetworkEvictionConfig, &out.NetworkEvictionConfig
		*out = new(NetworkEvictionConfig)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EvictionConfig.
func (in *EvictionConfig) DeepCopy() *EvictionConfig {
	if in == nil {
		return nil
	}
	out := new(EvictionConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GenericConfigCondition) DeepCopyInto(out *GenericConfigCondition) {
	*out = *in
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GenericConfigCondition.
func (in *GenericConfigCondition) DeepCopy() *GenericConfigCondition {
	if in == nil {
		return nil
	}
	out := new(GenericConfigCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GenericConfigSpec) DeepCopyInto(out *GenericConfigSpec) {
	*out = *in
	in.EphemeralSelector.DeepCopyInto(&out.EphemeralSelector)
	in.UpdateStrategy.DeepCopyInto(&out.UpdateStrategy)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GenericConfigSpec.
func (in *GenericConfigSpec) DeepCopy() *GenericConfigSpec {
	if in == nil {
		return nil
	}
	out := new(GenericConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GenericConfigStatus) DeepCopyInto(out *GenericConfigStatus) {
	*out = *in
	if in.CollisionCount != nil {
		in, out := &in.CollisionCount, &out.CollisionCount
		*out = new(int32)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]GenericConfigCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GenericConfigStatus.
func (in *GenericConfigStatus) DeepCopy() *GenericConfigStatus {
	if in == nil {
		return nil
	}
	out := new(GenericConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GlobalResourcePortraitConfiguration) DeepCopyInto(out *GlobalResourcePortraitConfiguration) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	if in.Configs != nil {
		in, out := &in.Configs, &out.Configs
		*out = make([]ResourcePortraitConfiguration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GlobalResourcePortraitConfiguration.
func (in *GlobalResourcePortraitConfiguration) DeepCopy() *GlobalResourcePortraitConfiguration {
	if in == nil {
		return nil
	}
	out := new(GlobalResourcePortraitConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GlobalResourcePortraitConfiguration) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GroupConfig) DeepCopyInto(out *GroupConfig) {
	*out = *in
	if in.Ratio != nil {
		in, out := &in.Ratio, &out.Ratio
		*out = new(float64)
		**out = **in
	}
	if in.EnabledStrategies != nil {
		in, out := &in.EnabledStrategies, &out.EnabledStrategies
		*out = make([]Strategy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GroupConfig.
func (in *GroupConfig) DeepCopy() *GroupConfig {
	if in == nil {
		return nil
	}
	out := new(GroupConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IRQCoreNetOverloadThresholds) DeepCopyInto(out *IRQCoreNetOverloadThresholds) {
	*out = *in
	if in.SoftNetTimeSqueezeRatio != nil {
		in, out := &in.SoftNetTimeSqueezeRatio, &out.SoftNetTimeSqueezeRatio
		*out = new(float64)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IRQCoreNetOverloadThresholds.
func (in *IRQCoreNetOverloadThresholds) DeepCopy() *IRQCoreNetOverloadThresholds {
	if in == nil {
		return nil
	}
	out := new(IRQCoreNetOverloadThresholds)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IRQCoresAdjustConfig) DeepCopyInto(out *IRQCoresAdjustConfig) {
	*out = *in
	if in.PercentMin != nil {
		in, out := &in.PercentMin, &out.PercentMin
		*out = new(int)
		**out = **in
	}
	if in.PercentMax != nil {
		in, out := &in.PercentMax, &out.PercentMax
		*out = new(int)
		**out = **in
	}
	if in.IncConf != nil {
		in, out := &in.IncConf, &out.IncConf
		*out = new(IRQCoresIncConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.DecConf != nil {
		in, out := &in.DecConf, &out.DecConf
		*out = new(IRQCoresDecConfig)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IRQCoresAdjustConfig.
func (in *IRQCoresAdjustConfig) DeepCopy() *IRQCoresAdjustConfig {
	if in == nil {
		return nil
	}
	out := new(IRQCoresAdjustConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IRQCoresDecConfig) DeepCopyInto(out *IRQCoresDecConfig) {
	*out = *in
	if in.SuccessiveDecInterval != nil {
		in, out := &in.SuccessiveDecInterval, &out.SuccessiveDecInterval
		*out = new(int)
		**out = **in
	}
	if in.PingPongAdjustInterval != nil {
		in, out := &in.PingPongAdjustInterval, &out.PingPongAdjustInterval
		*out = new(int)
		**out = **in
	}
	if in.SinceLastBalanceInterval != nil {
		in, out := &in.SinceLastBalanceInterval, &out.SinceLastBalanceInterval
		*out = new(int)
		**out = **in
	}
	if in.DecCoresMaxEachTime != nil {
		in, out := &in.DecCoresMaxEachTime, &out.DecCoresMaxEachTime
		*out = new(int)
		**out = **in
	}
	if in.Thresholds != nil {
		in, out := &in.Thresholds, &out.Thresholds
		*out = new(IRQCoresDecThresholds)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IRQCoresDecConfig.
func (in *IRQCoresDecConfig) DeepCopy() *IRQCoresDecConfig {
	if in == nil {
		return nil
	}
	out := new(IRQCoresDecConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IRQCoresDecThresholds) DeepCopyInto(out *IRQCoresDecThresholds) {
	*out = *in
	if in.AvgCPUUtilThreshold != nil {
		in, out := &in.AvgCPUUtilThreshold, &out.AvgCPUUtilThreshold
		*out = new(int)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IRQCoresDecThresholds.
func (in *IRQCoresDecThresholds) DeepCopy() *IRQCoresDecThresholds {
	if in == nil {
		return nil
	}
	out := new(IRQCoresDecThresholds)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IRQCoresExclusionConfig) DeepCopyInto(out *IRQCoresExclusionConfig) {
	*out = *in
	if in.Thresholds != nil {
		in, out := &in.Thresholds, &out.Thresholds
		*out = new(IRQCoresExclusionThresholds)
		(*in).DeepCopyInto(*out)
	}
	if in.SuccessiveSwitchInterval != nil {
		in, out := &in.SuccessiveSwitchInterval, &out.SuccessiveSwitchInterval
		*out = new(float64)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IRQCoresExclusionConfig.
func (in *IRQCoresExclusionConfig) DeepCopy() *IRQCoresExclusionConfig {
	if in == nil {
		return nil
	}
	out := new(IRQCoresExclusionConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IRQCoresExclusionThresholds) DeepCopyInto(out *IRQCoresExclusionThresholds) {
	*out = *in
	if in.EnableThresholds != nil {
		in, out := &in.EnableThresholds, &out.EnableThresholds
		*out = new(EnableIRQCoresExclusionThresholds)
		(*in).DeepCopyInto(*out)
	}
	if in.DisableThresholds != nil {
		in, out := &in.DisableThresholds, &out.DisableThresholds
		*out = new(DisableIRQCoresExclusionThresholds)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IRQCoresExclusionThresholds.
func (in *IRQCoresExclusionThresholds) DeepCopy() *IRQCoresExclusionThresholds {
	if in == nil {
		return nil
	}
	out := new(IRQCoresExclusionThresholds)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IRQCoresIncConfig) DeepCopyInto(out *IRQCoresIncConfig) {
	*out = *in
	if in.SuccessiveIncInterval != nil {
		in, out := &in.SuccessiveIncInterval, &out.SuccessiveIncInterval
		*out = new(int)
		**out = **in
	}
	if in.FullThreshold != nil {
		in, out := &in.FullThreshold, &out.FullThreshold
		*out = new(int)
		**out = **in
	}
	if in.Thresholds != nil {
		in, out := &in.Thresholds, &out.Thresholds
		*out = new(IRQCoresIncThresholds)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IRQCoresIncConfig.
func (in *IRQCoresIncConfig) DeepCopy() *IRQCoresIncConfig {
	if in == nil {
		return nil
	}
	out := new(IRQCoresIncConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IRQCoresIncThresholds) DeepCopyInto(out *IRQCoresIncThresholds) {
	*out = *in
	if in.AvgCPUUtilThreshold != nil {
		in, out := &in.AvgCPUUtilThreshold, &out.AvgCPUUtilThreshold
		*out = new(int)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IRQCoresIncThresholds.
func (in *IRQCoresIncThresholds) DeepCopy() *IRQCoresIncThresholds {
	if in == nil {
		return nil
	}
	out := new(IRQCoresIncThresholds)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IRQLoadBalanceConfig) DeepCopyInto(out *IRQLoadBalanceConfig) {
	*out = *in
	if in.SuccessiveTuningInterval != nil {
		in, out := &in.SuccessiveTuningInterval, &out.SuccessiveTuningInterval
		*out = new(int)
		**out = **in
	}
	if in.Thresholds != nil {
		in, out := &in.Thresholds, &out.Thresholds
		*out = new(IRQLoadBalanceTuningThresholds)
		(*in).DeepCopyInto(*out)
	}
	if in.PingPongIntervalThreshold != nil {
		in, out := &in.PingPongIntervalThreshold, &out.PingPongIntervalThreshold
		*out = new(int)
		**out = **in
	}
	if in.PingPongCountThreshold != nil {
		in, out := &in.PingPongCountThreshold, &out.PingPongCountThreshold
		*out = new(int)
		**out = **in
	}
	if in.IRQTunedNumMaxEachTime != nil {
		in, out := &in.IRQTunedNumMaxEachTime, &out.IRQTunedNumMaxEachTime
		*out = new(int)
		**out = **in
	}
	if in.IRQCoresTunedNumMaxEachTime != nil {
		in, out := &in.IRQCoresTunedNumMaxEachTime, &out.IRQCoresTunedNumMaxEachTime
		*out = new(int)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IRQLoadBalanceConfig.
func (in *IRQLoadBalanceConfig) DeepCopy() *IRQLoadBalanceConfig {
	if in == nil {
		return nil
	}
	out := new(IRQLoadBalanceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IRQLoadBalanceTuningThresholds) DeepCopyInto(out *IRQLoadBalanceTuningThresholds) {
	*out = *in
	if in.CPUUtilThreshold != nil {
		in, out := &in.CPUUtilThreshold, &out.CPUUtilThreshold
		*out = new(int)
		**out = **in
	}
	if in.CPUUtilGapThreshold != nil {
		in, out := &in.CPUUtilGapThreshold, &out.CPUUtilGapThreshold
		*out = new(int)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IRQLoadBalanceTuningThresholds.
func (in *IRQLoadBalanceTuningThresholds) DeepCopy() *IRQLoadBalanceTuningThresholds {
	if in == nil {
		return nil
	}
	out := new(IRQLoadBalanceTuningThresholds)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IRQTuningConfig) DeepCopyInto(out *IRQTuningConfig) {
	*out = *in
	if in.EnableTuner != nil {
		in, out := &in.EnableTuner, &out.EnableTuner
		*out = new(bool)
		**out = **in
	}
	if in.TuningInterval != nil {
		in, out := &in.TuningInterval, &out.TuningInterval
		*out = new(int)
		**out = **in
	}
	if in.EnableRPS != nil {
		in, out := &in.EnableRPS, &out.EnableRPS
		*out = new(bool)
		**out = **in
	}
	if in.EnableRPSCPUVSNicsQueue != nil {
		in, out := &in.EnableRPSCPUVSNicsQueue, &out.EnableRPSCPUVSNicsQueue
		*out = new(float64)
		**out = **in
	}
	if in.DisableXPS != nil {
		in, out := &in.DisableXPS, &out.DisableXPS
		*out = new(bool)
		**out = **in
	}
	if in.ReniceKsoftirqd != nil {
		in, out := &in.ReniceKsoftirqd, &out.ReniceKsoftirqd
		*out = new(bool)
		**out = **in
	}
	if in.KsoftirqdNice != nil {
		in, out := &in.KsoftirqdNice, &out.KsoftirqdNice
		*out = new(int)
		**out = **in
	}
	if in.CoresExpectedCPUUtil != nil {
		in, out := &in.CoresExpectedCPUUtil, &out.CoresExpectedCPUUtil
		*out = new(int)
		**out = **in
	}
	if in.RPSExcludeIRQCoresThreshold != nil {
		in, out := &in.RPSExcludeIRQCoresThreshold, &out.RPSExcludeIRQCoresThreshold
		*out = new(RPSExcludeIRQCoresThreshold)
		(*in).DeepCopyInto(*out)
	}
	if in.ThroughputClassSwitch != nil {
		in, out := &in.ThroughputClassSwitch, &out.ThroughputClassSwitch
		*out = new(ThroughputClassSwitchConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.CoreNetOverLoadThreshold != nil {
		in, out := &in.CoreNetOverLoadThreshold, &out.CoreNetOverLoadThreshold
		*out = new(IRQCoreNetOverloadThresholds)
		(*in).DeepCopyInto(*out)
	}
	if in.LoadBalance != nil {
		in, out := &in.LoadBalance, &out.LoadBalance
		*out = new(IRQLoadBalanceConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.CoresAdjust != nil {
		in, out := &in.CoresAdjust, &out.CoresAdjust
		*out = new(IRQCoresAdjustConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.CoresExclusion != nil {
		in, out := &in.CoresExclusion, &out.CoresExclusion
		*out = new(IRQCoresExclusionConfig)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IRQTuningConfig.
func (in *IRQTuningConfig) DeepCopy() *IRQTuningConfig {
	if in == nil {
		return nil
	}
	out := new(IRQTuningConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IRQTuningConfiguration) DeepCopyInto(out *IRQTuningConfiguration) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IRQTuningConfiguration.
func (in *IRQTuningConfiguration) DeepCopy() *IRQTuningConfiguration {
	if in == nil {
		return nil
	}
	out := new(IRQTuningConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IRQTuningConfiguration) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IRQTuningConfigurationList) DeepCopyInto(out *IRQTuningConfigurationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]IRQTuningConfiguration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IRQTuningConfigurationList.
func (in *IRQTuningConfigurationList) DeepCopy() *IRQTuningConfigurationList {
	if in == nil {
		return nil
	}
	out := new(IRQTuningConfigurationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IRQTuningConfigurationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IRQTuningConfigurationSpec) DeepCopyInto(out *IRQTuningConfigurationSpec) {
	*out = *in
	in.GenericConfigSpec.DeepCopyInto(&out.GenericConfigSpec)
	in.Config.DeepCopyInto(&out.Config)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IRQTuningConfigurationSpec.
func (in *IRQTuningConfigurationSpec) DeepCopy() *IRQTuningConfigurationSpec {
	if in == nil {
		return nil
	}
	out := new(IRQTuningConfigurationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IndicatorTargetConfiguration) DeepCopyInto(out *IndicatorTargetConfiguration) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IndicatorTargetConfiguration.
func (in *IndicatorTargetConfiguration) DeepCopy() *IndicatorTargetConfiguration {
	if in == nil {
		return nil
	}
	out := new(IndicatorTargetConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KatalystCustomConfig) DeepCopyInto(out *KatalystCustomConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KatalystCustomConfig.
func (in *KatalystCustomConfig) DeepCopy() *KatalystCustomConfig {
	if in == nil {
		return nil
	}
	out := new(KatalystCustomConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KatalystCustomConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KatalystCustomConfigCondition) DeepCopyInto(out *KatalystCustomConfigCondition) {
	*out = *in
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KatalystCustomConfigCondition.
func (in *KatalystCustomConfigCondition) DeepCopy() *KatalystCustomConfigCondition {
	if in == nil {
		return nil
	}
	out := new(KatalystCustomConfigCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KatalystCustomConfigList) DeepCopyInto(out *KatalystCustomConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KatalystCustomConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KatalystCustomConfigList.
func (in *KatalystCustomConfigList) DeepCopy() *KatalystCustomConfigList {
	if in == nil {
		return nil
	}
	out := new(KatalystCustomConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KatalystCustomConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KatalystCustomConfigSpec) DeepCopyInto(out *KatalystCustomConfigSpec) {
	*out = *in
	out.TargetType = in.TargetType
	if in.NodeLabelSelectorAllowedKeyList != nil {
		in, out := &in.NodeLabelSelectorAllowedKeyList, &out.NodeLabelSelectorAllowedKeyList
		*out = make([]PriorityNodeLabelSelectorAllowedKeyList, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KatalystCustomConfigSpec.
func (in *KatalystCustomConfigSpec) DeepCopy() *KatalystCustomConfigSpec {
	if in == nil {
		return nil
	}
	out := new(KatalystCustomConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KatalystCustomConfigStatus) DeepCopyInto(out *KatalystCustomConfigStatus) {
	*out = *in
	if in.InvalidTargetConfigList != nil {
		in, out := &in.InvalidTargetConfigList, &out.InvalidTargetConfigList
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]KatalystCustomConfigCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KatalystCustomConfigStatus.
func (in *KatalystCustomConfigStatus) DeepCopy() *KatalystCustomConfigStatus {
	if in == nil {
		return nil
	}
	out := new(KatalystCustomConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LowThroughputThresholds) DeepCopyInto(out *LowThroughputThresholds) {
	*out = *in
	if in.RxPPSThreshold != nil {
		in, out := &in.RxPPSThreshold, &out.RxPPSThreshold
		*out = new(uint64)
		**out = **in
	}
	if in.SuccessiveCount != nil {
		in, out := &in.SuccessiveCount, &out.SuccessiveCount
		*out = new(int)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LowThroughputThresholds.
func (in *LowThroughputThresholds) DeepCopy() *LowThroughputThresholds {
	if in == nil {
		return nil
	}
	out := new(LowThroughputThresholds)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MemoryAdvisorConfig) DeepCopyInto(out *MemoryAdvisorConfig) {
	*out = *in
	if in.MemoryGuardConfig != nil {
		in, out := &in.MemoryGuardConfig, &out.MemoryGuardConfig
		*out = new(MemoryGuardConfig)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MemoryAdvisorConfig.
func (in *MemoryAdvisorConfig) DeepCopy() *MemoryAdvisorConfig {
	if in == nil {
		return nil
	}
	out := new(MemoryAdvisorConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MemoryGuardConfig) DeepCopyInto(out *MemoryGuardConfig) {
	*out = *in
	if in.Enable != nil {
		in, out := &in.Enable, &out.Enable
		*out = new(bool)
		**out = **in
	}
	if in.CriticalWatermarkScaleFactor != nil {
		in, out := &in.CriticalWatermarkScaleFactor, &out.CriticalWatermarkScaleFactor
		*out = new(float64)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MemoryGuardConfig.
func (in *MemoryGuardConfig) DeepCopy() *MemoryGuardConfig {
	if in == nil {
		return nil
	}
	out := new(MemoryGuardConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MemoryHeadroomConfig) DeepCopyInto(out *MemoryHeadroomConfig) {
	*out = *in
	if in.UtilBasedConfig != nil {
		in, out := &in.UtilBasedConfig, &out.UtilBasedConfig
		*out = new(MemoryHeadroomUtilBasedConfig)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MemoryHeadroomConfig.
func (in *MemoryHeadroomConfig) DeepCopy() *MemoryHeadroomConfig {
	if in == nil {
		return nil
	}
	out := new(MemoryHeadroomConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MemoryHeadroomUtilBasedConfig) DeepCopyInto(out *MemoryHeadroomUtilBasedConfig) {
	*out = *in
	if in.Enable != nil {
		in, out := &in.Enable, &out.Enable
		*out = new(bool)
		**out = **in
	}
	if in.FreeBasedRatio != nil {
		in, out := &in.FreeBasedRatio, &out.FreeBasedRatio
		*out = new(float64)
		**out = **in
	}
	if in.StaticBasedCapacity != nil {
		in, out := &in.StaticBasedCapacity, &out.StaticBasedCapacity
		*out = new(float64)
		**out = **in
	}
	if in.CacheBasedRatio != nil {
		in, out := &in.CacheBasedRatio, &out.CacheBasedRatio
		*out = new(float64)
		**out = **in
	}
	if in.MaxOversoldRate != nil {
		in, out := &in.MaxOversoldRate, &out.MaxOversoldRate
		*out = new(float64)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MemoryHeadroomUtilBasedConfig.
func (in *MemoryHeadroomUtilBasedConfig) DeepCopy() *MemoryHeadroomUtilBasedConfig {
	if in == nil {
		return nil
	}
	out := new(MemoryHeadroomUtilBasedConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MemoryPressureEvictionConfig) DeepCopyInto(out *MemoryPressureEvictionConfig) {
	*out = *in
	if in.EnableNumaLevelEviction != nil {
		in, out := &in.EnableNumaLevelEviction, &out.EnableNumaLevelEviction
		*out = new(bool)
		**out = **in
	}
	if in.EnableSystemLevelEviction != nil {
		in, out := &in.EnableSystemLevelEviction, &out.EnableSystemLevelEviction
		*out = new(bool)
		**out = **in
	}
	if in.NumaVictimMinimumUtilizationThreshold != nil {
		in, out := &in.NumaVictimMinimumUtilizationThreshold, &out.NumaVictimMinimumUtilizationThreshold
		*out = new(float64)
		**out = **in
	}
	if in.NumaFreeBelowWatermarkTimesThreshold != nil {
		in, out := &in.NumaFreeBelowWatermarkTimesThreshold, &out.NumaFreeBelowWatermarkTimesThreshold
		*out = new(int)
		**out = **in
	}
	if in.NumaFreeBelowWatermarkTimesReclaimedThreshold != nil {
		in, out := &in.NumaFreeBelowWatermarkTimesReclaimedThreshold, &out.NumaFreeBelowWatermarkTimesReclaimedThreshold
		*out = new(int)
		**out = **in
	}
	if in.NumaFreeConstraintFastEvictionWaitCycle != nil {
		in, out := &in.NumaFreeConstraintFastEvictionWaitCycle, &out.NumaFreeConstraintFastEvictionWaitCycle
		*out = new(int)
		**out = **in
	}
	if in.SystemKswapdRateThreshold != nil {
		in, out := &in.SystemKswapdRateThreshold, &out.SystemKswapdRateThreshold
		*out = new(int)
		**out = **in
	}
	if in.SystemKswapdRateExceedDurationThreshold != nil {
		in, out := &in.SystemKswapdRateExceedDurationThreshold, &out.SystemKswapdRateExceedDurationThreshold
		*out = new(int)
		**out = **in
	}
	if in.SystemFreeMemoryThresholdMinimum != nil {
		in, out := &in.SystemFreeMemoryThresholdMinimum, &out.SystemFreeMemoryThresholdMinimum
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.NumaEvictionRankingMetrics != nil {
		in, out := &in.NumaEvictionRankingMetrics, &out.NumaEvictionRankingMetrics
		*out = make([]NumaEvictionRankingMetric, len(*in))
		copy(*out, *in)
	}
	if in.SystemEvictionRankingMetrics != nil {
		in, out := &in.SystemEvictionRankingMetrics, &out.SystemEvictionRankingMetrics
		*out = make([]SystemEvictionRankingMetric, len(*in))
		copy(*out, *in)
	}
	if in.EnableRSSOveruseEviction != nil {
		in, out := &in.EnableRSSOveruseEviction, &out.EnableRSSOveruseEviction
		*out = new(bool)
		**out = **in
	}
	if in.RSSOveruseRateThreshold != nil {
		in, out := &in.RSSOveruseRateThreshold, &out.RSSOveruseRateThreshold
		*out = new(float64)
		**out = **in
	}
	if in.GracePeriod != nil {
		in, out := &in.GracePeriod, &out.GracePeriod
		*out = new(int64)
		**out = **in
	}
	if in.ReclaimedGracePeriod != nil {
		in, out := &in.ReclaimedGracePeriod, &out.ReclaimedGracePeriod
		*out = new(int64)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MemoryPressureEvictionConfig.
func (in *MemoryPressureEvictionConfig) DeepCopy() *MemoryPressureEvictionConfig {
	if in == nil {
		return nil
	}
	out := new(MemoryPressureEvictionConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkEvictionConfig) DeepCopyInto(out *NetworkEvictionConfig) {
	*out = *in
	if in.EnableNICHealthEviction != nil {
		in, out := &in.EnableNICHealthEviction, &out.EnableNICHealthEviction
		*out = new(bool)
		**out = **in
	}
	if in.NICUnhealthyToleranceDuration != nil {
		in, out := &in.NICUnhealthyToleranceDuration, &out.NICUnhealthyToleranceDuration
		*out = new(v1.Duration)
		**out = **in
	}
	if in.GracePeriod != nil {
		in, out := &in.GracePeriod, &out.GracePeriod
		*out = new(int64)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkEvictionConfig.
func (in *NetworkEvictionConfig) DeepCopy() *NetworkEvictionConfig {
	if in == nil {
		return nil
	}
	out := new(NetworkEvictionConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NormalThroughputThresholds) DeepCopyInto(out *NormalThroughputThresholds) {
	*out = *in
	if in.RxPPSThreshold != nil {
		in, out := &in.RxPPSThreshold, &out.RxPPSThreshold
		*out = new(uint64)
		**out = **in
	}
	if in.SuccessiveCount != nil {
		in, out := &in.SuccessiveCount, &out.SuccessiveCount
		*out = new(int)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NormalThroughputThresholds.
func (in *NormalThroughputThresholds) DeepCopy() *NormalThroughputThresholds {
	if in == nil {
		return nil
	}
	out := new(NormalThroughputThresholds)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NumaCPUPressureEvictionConfig) DeepCopyInto(out *NumaCPUPressureEvictionConfig) {
	*out = *in
	if in.EnableEviction != nil {
		in, out := &in.EnableEviction, &out.EnableEviction
		*out = new(bool)
		**out = **in
	}
	if in.ThresholdMetPercentage != nil {
		in, out := &in.ThresholdMetPercentage, &out.ThresholdMetPercentage
		*out = new(float64)
		**out = **in
	}
	if in.MetricRingSize != nil {
		in, out := &in.MetricRingSize, &out.MetricRingSize
		*out = new(int)
		**out = **in
	}
	if in.GracePeriod != nil {
		in, out := &in.GracePeriod, &out.GracePeriod
		*out = new(int64)
		**out = **in
	}
	if in.ThresholdExpandFactor != nil {
		in, out := &in.ThresholdExpandFactor, &out.ThresholdExpandFactor
		*out = new(float64)
		**out = **in
	}
	if in.CandidateCount != nil {
		in, out := &in.CandidateCount, &out.CandidateCount
		*out = new(int)
		**out = **in
	}
	if in.SkippedPodKinds != nil {
		in, out := &in.SkippedPodKinds, &out.SkippedPodKinds
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NumaCPUPressureEvictionConfig.
func (in *NumaCPUPressureEvictionConfig) DeepCopy() *NumaCPUPressureEvictionConfig {
	if in == nil {
		return nil
	}
	out := new(NumaCPUPressureEvictionConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PSIPolicyConf) DeepCopyInto(out *PSIPolicyConf) {
	*out = *in
	if in.MaxProbe != nil {
		in, out := &in.MaxProbe, &out.MaxProbe
		*out = new(float64)
		**out = **in
	}
	if in.PSIAvg60Threshold != nil {
		in, out := &in.PSIAvg60Threshold, &out.PSIAvg60Threshold
		*out = new(float64)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PSIPolicyConf.
func (in *PSIPolicyConf) DeepCopy() *PSIPolicyConf {
	if in == nil {
		return nil
	}
	out := new(PSIPolicyConf)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyRule) DeepCopyInto(out *PolicyRule) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyRule.
func (in *PolicyRule) DeepCopy() *PolicyRule {
	if in == nil {
		return nil
	}
	out := new(PolicyRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PriorityNodeLabelSelectorAllowedKeyList) DeepCopyInto(out *PriorityNodeLabelSelectorAllowedKeyList) {
	*out = *in
	if in.KeyList != nil {
		in, out := &in.KeyList, &out.KeyList
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PriorityNodeLabelSelectorAllowedKeyList.
func (in *PriorityNodeLabelSelectorAllowedKeyList) DeepCopy() *PriorityNodeLabelSelectorAllowedKeyList {
	if in == nil {
		return nil
	}
	out := new(PriorityNodeLabelSelectorAllowedKeyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QoSLevelConfig) DeepCopyInto(out *QoSLevelConfig) {
	*out = *in
	in.ConfigDetail.DeepCopyInto(&out.ConfigDetail)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QoSLevelConfig.
func (in *QoSLevelConfig) DeepCopy() *QoSLevelConfig {
	if in == nil {
		return nil
	}
	out := new(QoSLevelConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RPSExcludeIRQCoresThreshold) DeepCopyInto(out *RPSExcludeIRQCoresThreshold) {
	*out = *in
	if in.RPSCoresVSIRQCoresRatio != nil {
		in, out := &in.RPSCoresVSIRQCoresRatio, &out.RPSCoresVSIRQCoresRatio
		*out = new(float64)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RPSExcludeIRQCoresThreshold.
func (in *RPSExcludeIRQCoresThreshold) DeepCopy() *RPSExcludeIRQCoresThreshold {
	if in == nil {
		return nil
	}
	out := new(RPSExcludeIRQCoresThreshold)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReclaimResourceIndicators) DeepCopyInto(out *ReclaimResourceIndicators) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	if in.DisableReclaimLevel != nil {
		in, out := &in.DisableReclaimLevel, &out.DisableReclaimLevel
		*out = new(DisableReclaimLevel)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReclaimResourceIndicators.
func (in *ReclaimResourceIndicators) DeepCopy() *ReclaimResourceIndicators {
	if in == nil {
		return nil
	}
	out := new(ReclaimResourceIndicators)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ReclaimResourceIndicators) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReclaimedResourceConfig) DeepCopyInto(out *ReclaimedResourceConfig) {
	*out = *in
	if in.EnableReclaim != nil {
		in, out := &in.EnableReclaim, &out.EnableReclaim
		*out = new(bool)
		**out = **in
	}
	if in.DisableReclaimSharePools != nil {
		in, out := &in.DisableReclaimSharePools, &out.DisableReclaimSharePools
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ReservedResourceForReport != nil {
		in, out := &in.ReservedResourceForReport, &out.ReservedResourceForReport
		*out = new(corev1.ResourceList)
		if **in != nil {
			in, out := *in, *out
			*out = make(map[corev1.ResourceName]resource.Quantity, len(*in))
			for key, val := range *in {
				(*out)[key] = val.DeepCopy()
			}
		}
	}
	if in.MinReclaimedResourceForReport != nil {
		in, out := &in.MinReclaimedResourceForReport, &out.MinReclaimedResourceForReport
		*out = new(corev1.ResourceList)
		if **in != nil {
			in, out := *in, *out
			*out = make(map[corev1.ResourceName]resource.Quantity, len(*in))
			for key, val := range *in {
				(*out)[key] = val.DeepCopy()
			}
		}
	}
	if in.MinIgnoredReclaimedResourceForReport != nil {
		in, out := &in.MinIgnoredReclaimedResourceForReport, &out.MinIgnoredReclaimedResourceForReport
		*out = new(corev1.ResourceList)
		if **in != nil {
			in, out := *in, *out
			*out = make(map[corev1.ResourceName]resource.Quantity, len(*in))
			for key, val := range *in {
				(*out)[key] = val.DeepCopy()
			}
		}
	}
	if in.ReservedResourceForAllocate != nil {
		in, out := &in.ReservedResourceForAllocate, &out.ReservedResourceForAllocate
		*out = new(corev1.ResourceList)
		if **in != nil {
			in, out := *in, *out
			*out = make(map[corev1.ResourceName]resource.Quantity, len(*in))
			for key, val := range *in {
				(*out)[key] = val.DeepCopy()
			}
		}
	}
	if in.MinReclaimedResourceForAllocate != nil {
		in, out := &in.MinReclaimedResourceForAllocate, &out.MinReclaimedResourceForAllocate
		*out = new(corev1.ResourceList)
		if **in != nil {
			in, out := *in, *out
			*out = make(map[corev1.ResourceName]resource.Quantity, len(*in))
			for key, val := range *in {
				(*out)[key] = val.DeepCopy()
			}
		}
	}
	if in.NumaMinReclaimedResourceRatioForAllocate != nil {
		in, out := &in.NumaMinReclaimedResourceRatioForAllocate, &out.NumaMinReclaimedResourceRatioForAllocate
		*out = new(corev1.ResourceList)
		if **in != nil {
			in, out := *in, *out
			*out = make(map[corev1.ResourceName]resource.Quantity, len(*in))
			for key, val := range *in {
				(*out)[key] = val.DeepCopy()
			}
		}
	}
	if in.NumaMinReclaimedResourceForAllocate != nil {
		in, out := &in.NumaMinReclaimedResourceForAllocate, &out.NumaMinReclaimedResourceForAllocate
		*out = new(corev1.ResourceList)
		if **in != nil {
			in, out := *in, *out
			*out = make(map[corev1.ResourceName]resource.Quantity, len(*in))
			for key, val := range *in {
				(*out)[key] = val.DeepCopy()
			}
		}
	}
	if in.CPUHeadroomConfig != nil {
		in, out := &in.CPUHeadroomConfig, &out.CPUHeadroomConfig
		*out = new(CPUHeadroomConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.MemoryHeadroomConfig != nil {
		in, out := &in.MemoryHeadroomConfig, &out.MemoryHeadroomConfig
		*out = new(MemoryHeadroomConfig)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReclaimedResourceConfig.
func (in *ReclaimedResourceConfig) DeepCopy() *ReclaimedResourceConfig {
	if in == nil {
		return nil
	}
	out := new(ReclaimedResourceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReclaimedResourcesEvictionConfig) DeepCopyInto(out *ReclaimedResourcesEvictionConfig) {
	*out = *in
	if in.EvictionThreshold != nil {
		in, out := &in.EvictionThreshold, &out.EvictionThreshold
		*out = make(map[corev1.ResourceName]float64, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.GracePeriod != nil {
		in, out := &in.GracePeriod, &out.GracePeriod
		*out = new(int64)
		**out = **in
	}
	if in.ThresholdMetToleranceDuration != nil {
		in, out := &in.ThresholdMetToleranceDuration, &out.ThresholdMetToleranceDuration
		*out = new(int64)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReclaimedResourcesEvictionConfig.
func (in *ReclaimedResourcesEvictionConfig) DeepCopy() *ReclaimedResourcesEvictionConfig {
	if in == nil {
		return nil
	}
	out := new(ReclaimedResourcesEvictionConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RefaultPolicyConf) DeepCopyInto(out *RefaultPolicyConf) {
	*out = *in
	if in.MaxProbe != nil {
		in, out := &in.MaxProbe, &out.MaxProbe
		*out = new(float64)
		**out = **in
	}
	if in.ReclaimAccuracyTarget != nil {
		in, out := &in.ReclaimAccuracyTarget, &out.ReclaimAccuracyTarget
		*out = new(float64)
		**out = **in
	}
	if in.ReclaimScanEfficiencyTarget != nil {
		in, out := &in.ReclaimScanEfficiencyTarget, &out.ReclaimScanEfficiencyTarget
		*out = new(float64)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RefaultPolicyConf.
func (in *RefaultPolicyConf) DeepCopy() *RefaultPolicyConf {
	if in == nil {
		return nil
	}
	out := new(RefaultPolicyConf)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RegionIndicators) DeepCopyInto(out *RegionIndicators) {
	*out = *in
	if in.Targets != nil {
		in, out := &in.Targets, &out.Targets
		*out = make([]IndicatorTargetConfiguration, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RegionIndicators.
func (in *RegionIndicators) DeepCopy() *RegionIndicators {
	if in == nil {
		return nil
	}
	out := new(RegionIndicators)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourcePortraitConfig) DeepCopyInto(out *ResourcePortraitConfig) {
	*out = *in
	in.AlgorithmConfig.DeepCopyInto(&out.AlgorithmConfig)
	if in.Metrics != nil {
		in, out := &in.Metrics, &out.Metrics
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.CustomMetrics != nil {
		in, out := &in.CustomMetrics, &out.CustomMetrics
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourcePortraitConfig.
func (in *ResourcePortraitConfig) DeepCopy() *ResourcePortraitConfig {
	if in == nil {
		return nil
	}
	out := new(ResourcePortraitConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourcePortraitConfiguration) DeepCopyInto(out *ResourcePortraitConfiguration) {
	*out = *in
	in.Config.DeepCopyInto(&out.Config)
	in.Filter.DeepCopyInto(&out.Filter)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourcePortraitConfiguration.
func (in *ResourcePortraitConfiguration) DeepCopy() *ResourcePortraitConfiguration {
	if in == nil {
		return nil
	}
	out := new(ResourcePortraitConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourcePortraitFilter) DeepCopyInto(out *ResourcePortraitFilter) {
	*out = *in
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Namespaces != nil {
		in, out := &in.Namespaces, &out.Namespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourcePortraitFilter.
func (in *ResourcePortraitFilter) DeepCopy() *ResourcePortraitFilter {
	if in == nil {
		return nil
	}
	out := new(ResourcePortraitFilter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourcePortraitIndicators) DeepCopyInto(out *ResourcePortraitIndicators) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	if in.Configs != nil {
		in, out := &in.Configs, &out.Configs
		*out = make([]ResourcePortraitConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourcePortraitIndicators.
func (in *ResourcePortraitIndicators) DeepCopy() *ResourcePortraitIndicators {
	if in == nil {
		return nil
	}
	out := new(ResourcePortraitIndicators)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ResourcePortraitIndicators) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestrictConstraints) DeepCopyInto(out *RestrictConstraints) {
	*out = *in
	if in.MaxUpperGap != nil {
		in, out := &in.MaxUpperGap, &out.MaxUpperGap
		*out = new(float64)
		**out = **in
	}
	if in.MaxLowerGap != nil {
		in, out := &in.MaxLowerGap, &out.MaxLowerGap
		*out = new(float64)
		**out = **in
	}
	if in.MaxUpperGapRatio != nil {
		in, out := &in.MaxUpperGapRatio, &out.MaxUpperGapRatio
		*out = new(float64)
		**out = **in
	}
	if in.MaxLowerGapRatio != nil {
		in, out := &in.MaxLowerGapRatio, &out.MaxLowerGapRatio
		*out = new(float64)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestrictConstraints.
func (in *RestrictConstraints) DeepCopy() *RestrictConstraints {
	if in == nil {
		return nil
	}
	out := new(RestrictConstraints)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RollingUpdateConfig) DeepCopyInto(out *RollingUpdateConfig) {
	*out = *in
	if in.Canary != nil {
		in, out := &in.Canary, &out.Canary
		*out = new(intstr.IntOrString)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RollingUpdateConfig.
func (in *RollingUpdateConfig) DeepCopy() *RollingUpdateConfig {
	if in == nil {
		return nil
	}
	out := new(RollingUpdateConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RootfsPressureEvictionConfig) DeepCopyInto(out *RootfsPressureEvictionConfig) {
	*out = *in
	if in.EnableRootfsPressureEviction != nil {
		in, out := &in.EnableRootfsPressureEviction, &out.EnableRootfsPressureEviction
		*out = new(bool)
		**out = **in
	}
	if in.MinimumImageFsFreeThreshold != nil {
		in, out := &in.MinimumImageFsFreeThreshold, &out.MinimumImageFsFreeThreshold
		*out = new(string)
		**out = **in
	}
	if in.MinimumImageFsInodesFreeThreshold != nil {
		in, out := &in.MinimumImageFsInodesFreeThreshold, &out.MinimumImageFsInodesFreeThreshold
		*out = new(string)
		**out = **in
	}
	if in.PodMinimumUsedThreshold != nil {
		in, out := &in.PodMinimumUsedThreshold, &out.PodMinimumUsedThreshold
		*out = new(string)
		**out = **in
	}
	if in.PodMinimumInodesUsedThreshold != nil {
		in, out := &in.PodMinimumInodesUsedThreshold, &out.PodMinimumInodesUsedThreshold
		*out = new(string)
		**out = **in
	}
	if in.ReclaimedQoSPodUsedPriorityThreshold != nil {
		in, out := &in.ReclaimedQoSPodUsedPriorityThreshold, &out.ReclaimedQoSPodUsedPriorityThreshold
		*out = new(string)
		**out = **in
	}
	if in.ReclaimedQoSPodInodesUsedPriorityThreshold != nil {
		in, out := &in.ReclaimedQoSPodInodesUsedPriorityThreshold, &out.ReclaimedQoSPodInodesUsedPriorityThreshold
		*out = new(string)
		**out = **in
	}
	if in.MinimumImageFsDiskCapacityThreshold != nil {
		in, out := &in.MinimumImageFsDiskCapacityThreshold, &out.MinimumImageFsDiskCapacityThreshold
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.GracePeriod != nil {
		in, out := &in.GracePeriod, &out.GracePeriod
		*out = new(int64)
		**out = **in
	}
	if in.EnableRootfsOveruseEviction != nil {
		in, out := &in.EnableRootfsOveruseEviction, &out.EnableRootfsOveruseEviction
		*out = new(bool)
		**out = **in
	}
	if in.RootfsOveruseEvictionSupportedQoSLevels != nil {
		in, out := &in.RootfsOveruseEvictionSupportedQoSLevels, &out.RootfsOveruseEvictionSupportedQoSLevels
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SharedQoSRootfsOveruseThreshold != nil {
		in, out := &in.SharedQoSRootfsOveruseThreshold, &out.SharedQoSRootfsOveruseThreshold
		*out = new(string)
		**out = **in
	}
	if in.ReclaimedQoSRootfsOveruseThreshold != nil {
		in, out := &in.ReclaimedQoSRootfsOveruseThreshold, &out.ReclaimedQoSRootfsOveruseThreshold
		*out = new(string)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RootfsPressureEvictionConfig.
func (in *RootfsPressureEvictionConfig) DeepCopy() *RootfsPressureEvictionConfig {
	if in == nil {
		return nil
	}
	out := new(RootfsPressureEvictionConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Strategy) DeepCopyInto(out *Strategy) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Parameters != nil {
		in, out := &in.Parameters, &out.Parameters
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Strategy.
func (in *Strategy) DeepCopy() *Strategy {
	if in == nil {
		return nil
	}
	out := new(Strategy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StrategyGroup) DeepCopyInto(out *StrategyGroup) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StrategyGroup.
func (in *StrategyGroup) DeepCopy() *StrategyGroup {
	if in == nil {
		return nil
	}
	out := new(StrategyGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StrategyGroup) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StrategyGroupConfig) DeepCopyInto(out *StrategyGroupConfig) {
	*out = *in
	if in.GroupConfigs != nil {
		in, out := &in.GroupConfigs, &out.GroupConfigs
		*out = make([]GroupConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StrategyGroupConfig.
func (in *StrategyGroupConfig) DeepCopy() *StrategyGroupConfig {
	if in == nil {
		return nil
	}
	out := new(StrategyGroupConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StrategyGroupConfiguration) DeepCopyInto(out *StrategyGroupConfiguration) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StrategyGroupConfiguration.
func (in *StrategyGroupConfiguration) DeepCopy() *StrategyGroupConfiguration {
	if in == nil {
		return nil
	}
	out := new(StrategyGroupConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StrategyGroupConfiguration) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StrategyGroupConfigurationList) DeepCopyInto(out *StrategyGroupConfigurationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]StrategyGroupConfiguration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StrategyGroupConfigurationList.
func (in *StrategyGroupConfigurationList) DeepCopy() *StrategyGroupConfigurationList {
	if in == nil {
		return nil
	}
	out := new(StrategyGroupConfigurationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StrategyGroupConfigurationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StrategyGroupConfigurationSpec) DeepCopyInto(out *StrategyGroupConfigurationSpec) {
	*out = *in
	in.GenericConfigSpec.DeepCopyInto(&out.GenericConfigSpec)
	in.Config.DeepCopyInto(&out.Config)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StrategyGroupConfigurationSpec.
func (in *StrategyGroupConfigurationSpec) DeepCopy() *StrategyGroupConfigurationSpec {
	if in == nil {
		return nil
	}
	out := new(StrategyGroupConfigurationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StrategyGroupList) DeepCopyInto(out *StrategyGroupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]StrategyGroup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StrategyGroupList.
func (in *StrategyGroupList) DeepCopy() *StrategyGroupList {
	if in == nil {
		return nil
	}
	out := new(StrategyGroupList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StrategyGroupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StrategyGroupStatus) DeepCopyInto(out *StrategyGroupStatus) {
	*out = *in
	in.GenericConfigStatus.DeepCopyInto(&out.GenericConfigStatus)
	if in.EnabledStrategies != nil {
		in, out := &in.EnabledStrategies, &out.EnabledStrategies
		*out = make([]Strategy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StrategyGroupStatus.
func (in *StrategyGroupStatus) DeepCopy() *StrategyGroupStatus {
	if in == nil {
		return nil
	}
	out := new(StrategyGroupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SystemLoadPressureEvictionConfig) DeepCopyInto(out *SystemLoadPressureEvictionConfig) {
	*out = *in
	if in.SoftThreshold != nil {
		in, out := &in.SoftThreshold, &out.SoftThreshold
		*out = new(int64)
		**out = **in
	}
	if in.HardThreshold != nil {
		in, out := &in.HardThreshold, &out.HardThreshold
		*out = new(int64)
		**out = **in
	}
	if in.HistorySize != nil {
		in, out := &in.HistorySize, &out.HistorySize
		*out = new(int64)
		**out = **in
	}
	if in.SyncPeriod != nil {
		in, out := &in.SyncPeriod, &out.SyncPeriod
		*out = new(int64)
		**out = **in
	}
	if in.CoolDownTime != nil {
		in, out := &in.CoolDownTime, &out.CoolDownTime
		*out = new(int64)
		**out = **in
	}
	if in.GracePeriod != nil {
		in, out := &in.GracePeriod, &out.GracePeriod
		*out = new(int64)
		**out = **in
	}
	if in.ThresholdMetPercentage != nil {
		in, out := &in.ThresholdMetPercentage, &out.ThresholdMetPercentage
		*out = new(float64)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SystemLoadPressureEvictionConfig.
func (in *SystemLoadPressureEvictionConfig) DeepCopy() *SystemLoadPressureEvictionConfig {
	if in == nil {
		return nil
	}
	out := new(SystemLoadPressureEvictionConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TMOConfigDetail) DeepCopyInto(out *TMOConfigDetail) {
	*out = *in
	if in.EnableTMO != nil {
		in, out := &in.EnableTMO, &out.EnableTMO
		*out = new(bool)
		**out = **in
	}
	if in.EnableSwap != nil {
		in, out := &in.EnableSwap, &out.EnableSwap
		*out = new(bool)
		**out = **in
	}
	if in.Interval != nil {
		in, out := &in.Interval, &out.Interval
		*out = new(v1.Duration)
		**out = **in
	}
	if in.PolicyName != nil {
		in, out := &in.PolicyName, &out.PolicyName
		*out = new(TMOPolicyName)
		**out = **in
	}
	if in.PSIPolicyConf != nil {
		in, out := &in.PSIPolicyConf, &out.PSIPolicyConf
		*out = new(PSIPolicyConf)
		(*in).DeepCopyInto(*out)
	}
	if in.RefaultPolicConf != nil {
		in, out := &in.RefaultPolicConf, &out.RefaultPolicConf
		*out = new(RefaultPolicyConf)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TMOConfigDetail.
func (in *TMOConfigDetail) DeepCopy() *TMOConfigDetail {
	if in == nil {
		return nil
	}
	out := new(TMOConfigDetail)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetConfig) DeepCopyInto(out *TargetConfig) {
	*out = *in
	out.ConfigType = in.ConfigType
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetConfig.
func (in *TargetConfig) DeepCopy() *TargetConfig {
	if in == nil {
		return nil
	}
	out := new(TargetConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThroughputClassSwitchConfig) DeepCopyInto(out *ThroughputClassSwitchConfig) {
	*out = *in
	if in.LowThroughputThresholds != nil {
		in, out := &in.LowThroughputThresholds, &out.LowThroughputThresholds
		*out = new(LowThroughputThresholds)
		(*in).DeepCopyInto(*out)
	}
	if in.NormalThroughputThresholds != nil {
		in, out := &in.NormalThroughputThresholds, &out.NormalThroughputThresholds
		*out = new(NormalThroughputThresholds)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThroughputClassSwitchConfig.
func (in *ThroughputClassSwitchConfig) DeepCopy() *ThroughputClassSwitchConfig {
	if in == nil {
		return nil
	}
	out := new(ThroughputClassSwitchConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TimeWindow) DeepCopyInto(out *TimeWindow) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TimeWindow.
func (in *TimeWindow) DeepCopy() *TimeWindow {
	if in == nil {
		return nil
	}
	out := new(TimeWindow)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransparentMemoryOffloadingConfig) DeepCopyInto(out *TransparentMemoryOffloadingConfig) {
	*out = *in
	if in.QoSLevelConfig != nil {
		in, out := &in.QoSLevelConfig, &out.QoSLevelConfig
		*out = make([]QoSLevelConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CgroupConfig != nil {
		in, out := &in.CgroupConfig, &out.CgroupConfig
		*out = make([]CgroupConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.BlockConfig != nil {
		in, out := &in.BlockConfig, &out.BlockConfig
		*out = new(BlockConfig)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransparentMemoryOffloadingConfig.
func (in *TransparentMemoryOffloadingConfig) DeepCopy() *TransparentMemoryOffloadingConfig {
	if in == nil {
		return nil
	}
	out := new(TransparentMemoryOffloadingConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransparentMemoryOffloadingConfiguration) DeepCopyInto(out *TransparentMemoryOffloadingConfiguration) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransparentMemoryOffloadingConfiguration.
func (in *TransparentMemoryOffloadingConfiguration) DeepCopy() *TransparentMemoryOffloadingConfiguration {
	if in == nil {
		return nil
	}
	out := new(TransparentMemoryOffloadingConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TransparentMemoryOffloadingConfiguration) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransparentMemoryOffloadingConfigurationList) DeepCopyInto(out *TransparentMemoryOffloadingConfigurationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TransparentMemoryOffloadingConfiguration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransparentMemoryOffloadingConfigurationList.
func (in *TransparentMemoryOffloadingConfigurationList) DeepCopy() *TransparentMemoryOffloadingConfigurationList {
	if in == nil {
		return nil
	}
	out := new(TransparentMemoryOffloadingConfigurationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TransparentMemoryOffloadingConfigurationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransparentMemoryOffloadingConfigurationSpec) DeepCopyInto(out *TransparentMemoryOffloadingConfigurationSpec) {
	*out = *in
	in.GenericConfigSpec.DeepCopyInto(&out.GenericConfigSpec)
	in.Config.DeepCopyInto(&out.Config)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransparentMemoryOffloadingConfigurationSpec.
func (in *TransparentMemoryOffloadingConfigurationSpec) DeepCopy() *TransparentMemoryOffloadingConfigurationSpec {
	if in == nil {
		return nil
	}
	out := new(TransparentMemoryOffloadingConfigurationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransparentMemoryOffloadingIndicators) DeepCopyInto(out *TransparentMemoryOffloadingIndicators) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	if in.ConfigDetail != nil {
		in, out := &in.ConfigDetail, &out.ConfigDetail
		*out = new(TMOConfigDetail)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransparentMemoryOffloadingIndicators.
func (in *TransparentMemoryOffloadingIndicators) DeepCopy() *TransparentMemoryOffloadingIndicators {
	if in == nil {
		return nil
	}
	out := new(TransparentMemoryOffloadingIndicators)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TransparentMemoryOffloadingIndicators) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserPasswordPair) DeepCopyInto(out *UserPasswordPair) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserPasswordPair.
func (in *UserPasswordPair) DeepCopy() *UserPasswordPair {
	if in == nil {
		return nil
	}
	out := new(UserPasswordPair)
	in.DeepCopyInto(out)
	return out
}
