/*
Copyright 2022 The Katalyst Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/kubewharf/katalyst-api/pkg/apis/config/v1alpha1"
	scheme "github.com/kubewharf/katalyst-api/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// StrategyGroupsGetter has a method to return a StrategyGroupInterface.
// A group's client should implement this interface.
type StrategyGroupsGetter interface {
	StrategyGroups() StrategyGroupInterface
}

// StrategyGroupInterface has methods to work with StrategyGroup resources.
type StrategyGroupInterface interface {
	Create(ctx context.Context, strategyGroup *v1alpha1.StrategyGroup, opts v1.CreateOptions) (*v1alpha1.StrategyGroup, error)
	Update(ctx context.Context, strategyGroup *v1alpha1.StrategyGroup, opts v1.UpdateOptions) (*v1alpha1.StrategyGroup, error)
	UpdateStatus(ctx context.Context, strategyGroup *v1alpha1.StrategyGroup, opts v1.UpdateOptions) (*v1alpha1.StrategyGroup, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.StrategyGroup, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.StrategyGroupList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.StrategyGroup, err error)
	StrategyGroupExpansion
}

// strategyGroups implements StrategyGroupInterface
type strategyGroups struct {
	client rest.Interface
}

// newStrategyGroups returns a StrategyGroups
func newStrategyGroups(c *ConfigV1alpha1Client) *strategyGroups {
	return &strategyGroups{
		client: c.RESTClient(),
	}
}

// Get takes name of the strategyGroup, and returns the corresponding strategyGroup object, and an error if there is any.
func (c *strategyGroups) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.StrategyGroup, err error) {
	result = &v1alpha1.StrategyGroup{}
	err = c.client.Get().
		Resource("strategygroups").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of StrategyGroups that match those selectors.
func (c *strategyGroups) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.StrategyGroupList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.StrategyGroupList{}
	err = c.client.Get().
		Resource("strategygroups").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested strategyGroups.
func (c *strategyGroups) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("strategygroups").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a strategyGroup and creates it.  Returns the server's representation of the strategyGroup, and an error, if there is any.
func (c *strategyGroups) Create(ctx context.Context, strategyGroup *v1alpha1.StrategyGroup, opts v1.CreateOptions) (result *v1alpha1.StrategyGroup, err error) {
	result = &v1alpha1.StrategyGroup{}
	err = c.client.Post().
		Resource("strategygroups").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(strategyGroup).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a strategyGroup and updates it. Returns the server's representation of the strategyGroup, and an error, if there is any.
func (c *strategyGroups) Update(ctx context.Context, strategyGroup *v1alpha1.StrategyGroup, opts v1.UpdateOptions) (result *v1alpha1.StrategyGroup, err error) {
	result = &v1alpha1.StrategyGroup{}
	err = c.client.Put().
		Resource("strategygroups").
		Name(strategyGroup.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(strategyGroup).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *strategyGroups) UpdateStatus(ctx context.Context, strategyGroup *v1alpha1.StrategyGroup, opts v1.UpdateOptions) (result *v1alpha1.StrategyGroup, err error) {
	result = &v1alpha1.StrategyGroup{}
	err = c.client.Put().
		Resource("strategygroups").
		Name(strategyGroup.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(strategyGroup).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the strategyGroup and deletes it. Returns an error if one occurs.
func (c *strategyGroups) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("strategygroups").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *strategyGroups) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("strategygroups").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched strategyGroup.
func (c *strategyGroups) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.StrategyGroup, err error) {
	result = &v1alpha1.StrategyGroup{}
	err = c.client.Patch(pt).
		Resource("strategygroups").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
