/*
Copyright 2022 The Katalyst Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha2 "github.com/kubewharf/katalyst-api/pkg/apis/autoscaling/v1alpha2"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeIntelligentHorizontalPodAutoscalers implements IntelligentHorizontalPodAutoscalerInterface
type FakeIntelligentHorizontalPodAutoscalers struct {
	Fake *FakeAutoscalingV1alpha2
	ns   string
}

var intelligenthorizontalpodautoscalersResource = schema.GroupVersionResource{Group: "autoscaling.katalyst.kubewharf.io", Version: "v1alpha2", Resource: "intelligenthorizontalpodautoscalers"}

var intelligenthorizontalpodautoscalersKind = schema.GroupVersionKind{Group: "autoscaling.katalyst.kubewharf.io", Version: "v1alpha2", Kind: "IntelligentHorizontalPodAutoscaler"}

// Get takes name of the intelligentHorizontalPodAutoscaler, and returns the corresponding intelligentHorizontalPodAutoscaler object, and an error if there is any.
func (c *FakeIntelligentHorizontalPodAutoscalers) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha2.IntelligentHorizontalPodAutoscaler, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(intelligenthorizontalpodautoscalersResource, c.ns, name), &v1alpha2.IntelligentHorizontalPodAutoscaler{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.IntelligentHorizontalPodAutoscaler), err
}

// List takes label and field selectors, and returns the list of IntelligentHorizontalPodAutoscalers that match those selectors.
func (c *FakeIntelligentHorizontalPodAutoscalers) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha2.IntelligentHorizontalPodAutoscalerList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(intelligenthorizontalpodautoscalersResource, intelligenthorizontalpodautoscalersKind, c.ns, opts), &v1alpha2.IntelligentHorizontalPodAutoscalerList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha2.IntelligentHorizontalPodAutoscalerList{ListMeta: obj.(*v1alpha2.IntelligentHorizontalPodAutoscalerList).ListMeta}
	for _, item := range obj.(*v1alpha2.IntelligentHorizontalPodAutoscalerList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested intelligentHorizontalPodAutoscalers.
func (c *FakeIntelligentHorizontalPodAutoscalers) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(intelligenthorizontalpodautoscalersResource, c.ns, opts))

}

// Create takes the representation of a intelligentHorizontalPodAutoscaler and creates it.  Returns the server's representation of the intelligentHorizontalPodAutoscaler, and an error, if there is any.
func (c *FakeIntelligentHorizontalPodAutoscalers) Create(ctx context.Context, intelligentHorizontalPodAutoscaler *v1alpha2.IntelligentHorizontalPodAutoscaler, opts v1.CreateOptions) (result *v1alpha2.IntelligentHorizontalPodAutoscaler, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(intelligenthorizontalpodautoscalersResource, c.ns, intelligentHorizontalPodAutoscaler), &v1alpha2.IntelligentHorizontalPodAutoscaler{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.IntelligentHorizontalPodAutoscaler), err
}

// Update takes the representation of a intelligentHorizontalPodAutoscaler and updates it. Returns the server's representation of the intelligentHorizontalPodAutoscaler, and an error, if there is any.
func (c *FakeIntelligentHorizontalPodAutoscalers) Update(ctx context.Context, intelligentHorizontalPodAutoscaler *v1alpha2.IntelligentHorizontalPodAutoscaler, opts v1.UpdateOptions) (result *v1alpha2.IntelligentHorizontalPodAutoscaler, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(intelligenthorizontalpodautoscalersResource, c.ns, intelligentHorizontalPodAutoscaler), &v1alpha2.IntelligentHorizontalPodAutoscaler{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.IntelligentHorizontalPodAutoscaler), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeIntelligentHorizontalPodAutoscalers) UpdateStatus(ctx context.Context, intelligentHorizontalPodAutoscaler *v1alpha2.IntelligentHorizontalPodAutoscaler, opts v1.UpdateOptions) (*v1alpha2.IntelligentHorizontalPodAutoscaler, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(intelligenthorizontalpodautoscalersResource, "status", c.ns, intelligentHorizontalPodAutoscaler), &v1alpha2.IntelligentHorizontalPodAutoscaler{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.IntelligentHorizontalPodAutoscaler), err
}

// Delete takes name of the intelligentHorizontalPodAutoscaler and deletes it. Returns an error if one occurs.
func (c *FakeIntelligentHorizontalPodAutoscalers) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(intelligenthorizontalpodautoscalersResource, c.ns, name, opts), &v1alpha2.IntelligentHorizontalPodAutoscaler{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeIntelligentHorizontalPodAutoscalers) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(intelligenthorizontalpodautoscalersResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha2.IntelligentHorizontalPodAutoscalerList{})
	return err
}

// Patch applies the patch and returns the patched intelligentHorizontalPodAutoscaler.
func (c *FakeIntelligentHorizontalPodAutoscalers) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha2.IntelligentHorizontalPodAutoscaler, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(intelligenthorizontalpodautoscalersResource, c.ns, name, pt, data, subresources...), &v1alpha2.IntelligentHorizontalPodAutoscaler{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.IntelligentHorizontalPodAutoscaler), err
}
