/*
Copyright 2022 The Katalyst Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha2 "github.com/kubewharf/katalyst-api/pkg/apis/autoscaling/v1alpha2"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeVirtualWorkloads implements VirtualWorkloadInterface
type FakeVirtualWorkloads struct {
	Fake *FakeAutoscalingV1alpha2
	ns   string
}

var virtualworkloadsResource = schema.GroupVersionResource{Group: "autoscaling.katalyst.kubewharf.io", Version: "v1alpha2", Resource: "virtualworkloads"}

var virtualworkloadsKind = schema.GroupVersionKind{Group: "autoscaling.katalyst.kubewharf.io", Version: "v1alpha2", Kind: "VirtualWorkload"}

// Get takes name of the virtualWorkload, and returns the corresponding virtualWorkload object, and an error if there is any.
func (c *FakeVirtualWorkloads) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha2.VirtualWorkload, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(virtualworkloadsResource, c.ns, name), &v1alpha2.VirtualWorkload{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.VirtualWorkload), err
}

// List takes label and field selectors, and returns the list of VirtualWorkloads that match those selectors.
func (c *FakeVirtualWorkloads) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha2.VirtualWorkloadList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(virtualworkloadsResource, virtualworkloadsKind, c.ns, opts), &v1alpha2.VirtualWorkloadList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha2.VirtualWorkloadList{ListMeta: obj.(*v1alpha2.VirtualWorkloadList).ListMeta}
	for _, item := range obj.(*v1alpha2.VirtualWorkloadList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested virtualWorkloads.
func (c *FakeVirtualWorkloads) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(virtualworkloadsResource, c.ns, opts))

}

// Create takes the representation of a virtualWorkload and creates it.  Returns the server's representation of the virtualWorkload, and an error, if there is any.
func (c *FakeVirtualWorkloads) Create(ctx context.Context, virtualWorkload *v1alpha2.VirtualWorkload, opts v1.CreateOptions) (result *v1alpha2.VirtualWorkload, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(virtualworkloadsResource, c.ns, virtualWorkload), &v1alpha2.VirtualWorkload{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.VirtualWorkload), err
}

// Update takes the representation of a virtualWorkload and updates it. Returns the server's representation of the virtualWorkload, and an error, if there is any.
func (c *FakeVirtualWorkloads) Update(ctx context.Context, virtualWorkload *v1alpha2.VirtualWorkload, opts v1.UpdateOptions) (result *v1alpha2.VirtualWorkload, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(virtualworkloadsResource, c.ns, virtualWorkload), &v1alpha2.VirtualWorkload{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.VirtualWorkload), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeVirtualWorkloads) UpdateStatus(ctx context.Context, virtualWorkload *v1alpha2.VirtualWorkload, opts v1.UpdateOptions) (*v1alpha2.VirtualWorkload, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(virtualworkloadsResource, "status", c.ns, virtualWorkload), &v1alpha2.VirtualWorkload{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.VirtualWorkload), err
}

// Delete takes name of the virtualWorkload and deletes it. Returns an error if one occurs.
func (c *FakeVirtualWorkloads) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(virtualworkloadsResource, c.ns, name, opts), &v1alpha2.VirtualWorkload{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeVirtualWorkloads) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(virtualworkloadsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha2.VirtualWorkloadList{})
	return err
}

// Patch applies the patch and returns the patched virtualWorkload.
func (c *FakeVirtualWorkloads) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha2.VirtualWorkload, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(virtualworkloadsResource, c.ns, name, pt, data, subresources...), &v1alpha2.VirtualWorkload{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.VirtualWorkload), err
}
