/*
Copyright 2022 The Katalyst Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/kubewharf/katalyst-api/pkg/apis/config/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// StrategyGroupConfigurationLister helps list StrategyGroupConfigurations.
type StrategyGroupConfigurationLister interface {
	// List lists all StrategyGroupConfigurations in the indexer.
	List(selector labels.Selector) (ret []*v1alpha1.StrategyGroupConfiguration, err error)
	// Get retrieves the StrategyGroupConfiguration from the index for a given name.
	Get(name string) (*v1alpha1.StrategyGroupConfiguration, error)
	StrategyGroupConfigurationListerExpansion
}

// strategyGroupConfigurationLister implements the StrategyGroupConfigurationLister interface.
type strategyGroupConfigurationLister struct {
	indexer cache.Indexer
}

// NewStrategyGroupConfigurationLister returns a new StrategyGroupConfigurationLister.
func NewStrategyGroupConfigurationLister(indexer cache.Indexer) StrategyGroupConfigurationLister {
	return &strategyGroupConfigurationLister{indexer: indexer}
}

// List lists all StrategyGroupConfigurations in the indexer.
func (s *strategyGroupConfigurationLister) List(selector labels.Selector) (ret []*v1alpha1.StrategyGroupConfiguration, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.StrategyGroupConfiguration))
	})
	return ret, err
}

// Get retrieves the StrategyGroupConfiguration from the index for a given name.
func (s *strategyGroupConfigurationLister) Get(name string) (*v1alpha1.StrategyGroupConfiguration, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("strategygroupconfiguration"), name)
	}
	return obj.(*v1alpha1.StrategyGroupConfiguration), nil
}
