/*
Copyright 2022 The Katalyst Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/kubewharf/katalyst-api/pkg/apis/config/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// StrategyGroupLister helps list StrategyGroups.
// All objects returned here must be treated as read-only.
type StrategyGroupLister interface {
	// List lists all StrategyGroups in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.StrategyGroup, err error)
	// Get retrieves the StrategyGroup from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.StrategyGroup, error)
	StrategyGroupListerExpansion
}

// strategyGroupLister implements the StrategyGroupLister interface.
type strategyGroupLister struct {
	indexer cache.Indexer
}

// NewStrategyGroupLister returns a new StrategyGroupLister.
func NewStrategyGroupLister(indexer cache.Indexer) StrategyGroupLister {
	return &strategyGroupLister{indexer: indexer}
}

// List lists all StrategyGroups in the indexer.
func (s *strategyGroupLister) List(selector labels.Selector) (ret []*v1alpha1.StrategyGroup, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.StrategyGroup))
	})
	return ret, err
}

// Get retrieves the StrategyGroup from the index for a given name.
func (s *strategyGroupLister) Get(name string) (*v1alpha1.StrategyGroup, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("strategygroup"), name)
	}
	return obj.(*v1alpha1.StrategyGroup), nil
}
