//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2022 The Katalyst Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v1beta3

import (
	unsafe "unsafe"

	config "github.com/kubewharf/katalyst-api/pkg/apis/scheduling/config"
	consts "github.com/kubewharf/katalyst-api/pkg/consts"
	v1 "k8s.io/api/core/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	configv1beta3 "k8s.io/kube-scheduler/config/v1beta3"
	apisconfig "k8s.io/kubernetes/pkg/scheduler/apis/config"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*LoadAwareArgs)(nil), (*config.LoadAwareArgs)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta3_LoadAwareArgs_To_config_LoadAwareArgs(a.(*LoadAwareArgs), b.(*config.LoadAwareArgs), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.LoadAwareArgs)(nil), (*LoadAwareArgs)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_LoadAwareArgs_To_v1beta3_LoadAwareArgs(a.(*config.LoadAwareArgs), b.(*LoadAwareArgs), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*NodeResourceTopologyArgs)(nil), (*config.NodeResourceTopologyArgs)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta3_NodeResourceTopologyArgs_To_config_NodeResourceTopologyArgs(a.(*NodeResourceTopologyArgs), b.(*config.NodeResourceTopologyArgs), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.NodeResourceTopologyArgs)(nil), (*NodeResourceTopologyArgs)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_NodeResourceTopologyArgs_To_v1beta3_NodeResourceTopologyArgs(a.(*config.NodeResourceTopologyArgs), b.(*NodeResourceTopologyArgs), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*QoSAwareNodeResourcesBalancedAllocationArgs)(nil), (*config.QoSAwareNodeResourcesBalancedAllocationArgs)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta3_QoSAwareNodeResourcesBalancedAllocationArgs_To_config_QoSAwareNodeResourcesBalancedAllocationArgs(a.(*QoSAwareNodeResourcesBalancedAllocationArgs), b.(*config.QoSAwareNodeResourcesBalancedAllocationArgs), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.QoSAwareNodeResourcesBalancedAllocationArgs)(nil), (*QoSAwareNodeResourcesBalancedAllocationArgs)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_QoSAwareNodeResourcesBalancedAllocationArgs_To_v1beta3_QoSAwareNodeResourcesBalancedAllocationArgs(a.(*config.QoSAwareNodeResourcesBalancedAllocationArgs), b.(*QoSAwareNodeResourcesBalancedAllocationArgs), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*QoSAwareNodeResourcesFitArgs)(nil), (*config.QoSAwareNodeResourcesFitArgs)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta3_QoSAwareNodeResourcesFitArgs_To_config_QoSAwareNodeResourcesFitArgs(a.(*QoSAwareNodeResourcesFitArgs), b.(*config.QoSAwareNodeResourcesFitArgs), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.QoSAwareNodeResourcesFitArgs)(nil), (*QoSAwareNodeResourcesFitArgs)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_QoSAwareNodeResourcesFitArgs_To_v1beta3_QoSAwareNodeResourcesFitArgs(a.(*config.QoSAwareNodeResourcesFitArgs), b.(*QoSAwareNodeResourcesFitArgs), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ScoringStrategy)(nil), (*config.ScoringStrategy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta3_ScoringStrategy_To_config_ScoringStrategy(a.(*ScoringStrategy), b.(*config.ScoringStrategy), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.ScoringStrategy)(nil), (*ScoringStrategy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_ScoringStrategy_To_v1beta3_ScoringStrategy(a.(*config.ScoringStrategy), b.(*ScoringStrategy), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1beta3_LoadAwareArgs_To_config_LoadAwareArgs(in *LoadAwareArgs, out *config.LoadAwareArgs, s conversion.Scope) error {
	out.EnablePortrait = (*bool)(unsafe.Pointer(in.EnablePortrait))
	out.PodAnnotationLoadAwareEnable = (*string)(unsafe.Pointer(in.PodAnnotationLoadAwareEnable))
	out.FilterExpiredNodeMetrics = (*bool)(unsafe.Pointer(in.FilterExpiredNodeMetrics))
	out.NodeMetricsExpiredSeconds = (*int64)(unsafe.Pointer(in.NodeMetricsExpiredSeconds))
	out.ResourceToWeightMap = *(*map[v1.ResourceName]int64)(unsafe.Pointer(&in.ResourceToWeightMap))
	out.ResourceToThresholdMap = *(*map[v1.ResourceName]int64)(unsafe.Pointer(&in.ResourceToThresholdMap))
	out.ResourceToScalingFactorMap = *(*map[v1.ResourceName]int64)(unsafe.Pointer(&in.ResourceToScalingFactorMap))
	out.ResourceToTargetMap = *(*map[v1.ResourceName]int64)(unsafe.Pointer(&in.ResourceToTargetMap))
	out.CalculateIndicatorWeight = *(*map[config.IndicatorType]int64)(unsafe.Pointer(&in.CalculateIndicatorWeight))
	out.KubeConfigPath = in.KubeConfigPath
	return nil
}

// Convert_v1beta3_LoadAwareArgs_To_config_LoadAwareArgs is an autogenerated conversion function.
func Convert_v1beta3_LoadAwareArgs_To_config_LoadAwareArgs(in *LoadAwareArgs, out *config.LoadAwareArgs, s conversion.Scope) error {
	return autoConvert_v1beta3_LoadAwareArgs_To_config_LoadAwareArgs(in, out, s)
}

func autoConvert_config_LoadAwareArgs_To_v1beta3_LoadAwareArgs(in *config.LoadAwareArgs, out *LoadAwareArgs, s conversion.Scope) error {
	out.EnablePortrait = (*bool)(unsafe.Pointer(in.EnablePortrait))
	out.PodAnnotationLoadAwareEnable = (*string)(unsafe.Pointer(in.PodAnnotationLoadAwareEnable))
	out.FilterExpiredNodeMetrics = (*bool)(unsafe.Pointer(in.FilterExpiredNodeMetrics))
	out.NodeMetricsExpiredSeconds = (*int64)(unsafe.Pointer(in.NodeMetricsExpiredSeconds))
	out.ResourceToWeightMap = *(*map[v1.ResourceName]int64)(unsafe.Pointer(&in.ResourceToWeightMap))
	out.ResourceToThresholdMap = *(*map[v1.ResourceName]int64)(unsafe.Pointer(&in.ResourceToThresholdMap))
	out.ResourceToScalingFactorMap = *(*map[v1.ResourceName]int64)(unsafe.Pointer(&in.ResourceToScalingFactorMap))
	out.ResourceToTargetMap = *(*map[v1.ResourceName]int64)(unsafe.Pointer(&in.ResourceToTargetMap))
	out.CalculateIndicatorWeight = *(*map[IndicatorType]int64)(unsafe.Pointer(&in.CalculateIndicatorWeight))
	out.KubeConfigPath = in.KubeConfigPath
	return nil
}

// Convert_config_LoadAwareArgs_To_v1beta3_LoadAwareArgs is an autogenerated conversion function.
func Convert_config_LoadAwareArgs_To_v1beta3_LoadAwareArgs(in *config.LoadAwareArgs, out *LoadAwareArgs, s conversion.Scope) error {
	return autoConvert_config_LoadAwareArgs_To_v1beta3_LoadAwareArgs(in, out, s)
}

func autoConvert_v1beta3_NodeResourceTopologyArgs_To_config_NodeResourceTopologyArgs(in *NodeResourceTopologyArgs, out *config.NodeResourceTopologyArgs, s conversion.Scope) error {
	out.ScoringStrategy = (*config.ScoringStrategy)(unsafe.Pointer(in.ScoringStrategy))
	out.AlignedResources = *(*[]string)(unsafe.Pointer(&in.AlignedResources))
	out.ResourcePluginPolicy = consts.ResourcePluginPolicyName(in.ResourcePluginPolicy)
	return nil
}

// Convert_v1beta3_NodeResourceTopologyArgs_To_config_NodeResourceTopologyArgs is an autogenerated conversion function.
func Convert_v1beta3_NodeResourceTopologyArgs_To_config_NodeResourceTopologyArgs(in *NodeResourceTopologyArgs, out *config.NodeResourceTopologyArgs, s conversion.Scope) error {
	return autoConvert_v1beta3_NodeResourceTopologyArgs_To_config_NodeResourceTopologyArgs(in, out, s)
}

func autoConvert_config_NodeResourceTopologyArgs_To_v1beta3_NodeResourceTopologyArgs(in *config.NodeResourceTopologyArgs, out *NodeResourceTopologyArgs, s conversion.Scope) error {
	out.ScoringStrategy = (*ScoringStrategy)(unsafe.Pointer(in.ScoringStrategy))
	out.AlignedResources = *(*[]string)(unsafe.Pointer(&in.AlignedResources))
	out.ResourcePluginPolicy = consts.ResourcePluginPolicyName(in.ResourcePluginPolicy)
	return nil
}

// Convert_config_NodeResourceTopologyArgs_To_v1beta3_NodeResourceTopologyArgs is an autogenerated conversion function.
func Convert_config_NodeResourceTopologyArgs_To_v1beta3_NodeResourceTopologyArgs(in *config.NodeResourceTopologyArgs, out *NodeResourceTopologyArgs, s conversion.Scope) error {
	return autoConvert_config_NodeResourceTopologyArgs_To_v1beta3_NodeResourceTopologyArgs(in, out, s)
}

func autoConvert_v1beta3_QoSAwareNodeResourcesBalancedAllocationArgs_To_config_QoSAwareNodeResourcesBalancedAllocationArgs(in *QoSAwareNodeResourcesBalancedAllocationArgs, out *config.QoSAwareNodeResourcesBalancedAllocationArgs, s conversion.Scope) error {
	out.Resources = *(*[]apisconfig.ResourceSpec)(unsafe.Pointer(&in.Resources))
	out.ReclaimedResources = *(*[]apisconfig.ResourceSpec)(unsafe.Pointer(&in.ReclaimedResources))
	return nil
}

// Convert_v1beta3_QoSAwareNodeResourcesBalancedAllocationArgs_To_config_QoSAwareNodeResourcesBalancedAllocationArgs is an autogenerated conversion function.
func Convert_v1beta3_QoSAwareNodeResourcesBalancedAllocationArgs_To_config_QoSAwareNodeResourcesBalancedAllocationArgs(in *QoSAwareNodeResourcesBalancedAllocationArgs, out *config.QoSAwareNodeResourcesBalancedAllocationArgs, s conversion.Scope) error {
	return autoConvert_v1beta3_QoSAwareNodeResourcesBalancedAllocationArgs_To_config_QoSAwareNodeResourcesBalancedAllocationArgs(in, out, s)
}

func autoConvert_config_QoSAwareNodeResourcesBalancedAllocationArgs_To_v1beta3_QoSAwareNodeResourcesBalancedAllocationArgs(in *config.QoSAwareNodeResourcesBalancedAllocationArgs, out *QoSAwareNodeResourcesBalancedAllocationArgs, s conversion.Scope) error {
	out.Resources = *(*[]configv1beta3.ResourceSpec)(unsafe.Pointer(&in.Resources))
	out.ReclaimedResources = *(*[]configv1beta3.ResourceSpec)(unsafe.Pointer(&in.ReclaimedResources))
	return nil
}

// Convert_config_QoSAwareNodeResourcesBalancedAllocationArgs_To_v1beta3_QoSAwareNodeResourcesBalancedAllocationArgs is an autogenerated conversion function.
func Convert_config_QoSAwareNodeResourcesBalancedAllocationArgs_To_v1beta3_QoSAwareNodeResourcesBalancedAllocationArgs(in *config.QoSAwareNodeResourcesBalancedAllocationArgs, out *QoSAwareNodeResourcesBalancedAllocationArgs, s conversion.Scope) error {
	return autoConvert_config_QoSAwareNodeResourcesBalancedAllocationArgs_To_v1beta3_QoSAwareNodeResourcesBalancedAllocationArgs(in, out, s)
}

func autoConvert_v1beta3_QoSAwareNodeResourcesFitArgs_To_config_QoSAwareNodeResourcesFitArgs(in *QoSAwareNodeResourcesFitArgs, out *config.QoSAwareNodeResourcesFitArgs, s conversion.Scope) error {
	out.ScoringStrategy = (*config.ScoringStrategy)(unsafe.Pointer(in.ScoringStrategy))
	return nil
}

// Convert_v1beta3_QoSAwareNodeResourcesFitArgs_To_config_QoSAwareNodeResourcesFitArgs is an autogenerated conversion function.
func Convert_v1beta3_QoSAwareNodeResourcesFitArgs_To_config_QoSAwareNodeResourcesFitArgs(in *QoSAwareNodeResourcesFitArgs, out *config.QoSAwareNodeResourcesFitArgs, s conversion.Scope) error {
	return autoConvert_v1beta3_QoSAwareNodeResourcesFitArgs_To_config_QoSAwareNodeResourcesFitArgs(in, out, s)
}

func autoConvert_config_QoSAwareNodeResourcesFitArgs_To_v1beta3_QoSAwareNodeResourcesFitArgs(in *config.QoSAwareNodeResourcesFitArgs, out *QoSAwareNodeResourcesFitArgs, s conversion.Scope) error {
	out.ScoringStrategy = (*ScoringStrategy)(unsafe.Pointer(in.ScoringStrategy))
	return nil
}

// Convert_config_QoSAwareNodeResourcesFitArgs_To_v1beta3_QoSAwareNodeResourcesFitArgs is an autogenerated conversion function.
func Convert_config_QoSAwareNodeResourcesFitArgs_To_v1beta3_QoSAwareNodeResourcesFitArgs(in *config.QoSAwareNodeResourcesFitArgs, out *QoSAwareNodeResourcesFitArgs, s conversion.Scope) error {
	return autoConvert_config_QoSAwareNodeResourcesFitArgs_To_v1beta3_QoSAwareNodeResourcesFitArgs(in, out, s)
}

func autoConvert_v1beta3_ScoringStrategy_To_config_ScoringStrategy(in *ScoringStrategy, out *config.ScoringStrategy, s conversion.Scope) error {
	out.Type = apisconfig.ScoringStrategyType(in.Type)
	out.Resources = *(*[]apisconfig.ResourceSpec)(unsafe.Pointer(&in.Resources))
	out.ReclaimedResources = *(*[]apisconfig.ResourceSpec)(unsafe.Pointer(&in.ReclaimedResources))
	out.RequestedToCapacityRatio = (*apisconfig.RequestedToCapacityRatioParam)(unsafe.Pointer(in.RequestedToCapacityRatio))
	out.ReclaimedRequestedToCapacityRatio = (*apisconfig.RequestedToCapacityRatioParam)(unsafe.Pointer(in.ReclaimedRequestedToCapacityRatio))
	return nil
}

// Convert_v1beta3_ScoringStrategy_To_config_ScoringStrategy is an autogenerated conversion function.
func Convert_v1beta3_ScoringStrategy_To_config_ScoringStrategy(in *ScoringStrategy, out *config.ScoringStrategy, s conversion.Scope) error {
	return autoConvert_v1beta3_ScoringStrategy_To_config_ScoringStrategy(in, out, s)
}

func autoConvert_config_ScoringStrategy_To_v1beta3_ScoringStrategy(in *config.ScoringStrategy, out *ScoringStrategy, s conversion.Scope) error {
	out.Type = configv1beta3.ScoringStrategyType(in.Type)
	out.Resources = *(*[]configv1beta3.ResourceSpec)(unsafe.Pointer(&in.Resources))
	out.ReclaimedResources = *(*[]configv1beta3.ResourceSpec)(unsafe.Pointer(&in.ReclaimedResources))
	out.RequestedToCapacityRatio = (*configv1beta3.RequestedToCapacityRatioParam)(unsafe.Pointer(in.RequestedToCapacityRatio))
	out.ReclaimedRequestedToCapacityRatio = (*configv1beta3.RequestedToCapacityRatioParam)(unsafe.Pointer(in.ReclaimedRequestedToCapacityRatio))
	return nil
}

// Convert_config_ScoringStrategy_To_v1beta3_ScoringStrategy is an autogenerated conversion function.
func Convert_config_ScoringStrategy_To_v1beta3_ScoringStrategy(in *config.ScoringStrategy, out *ScoringStrategy, s conversion.Scope) error {
	return autoConvert_config_ScoringStrategy_To_v1beta3_ScoringStrategy(in, out, s)
}
