/*
Copyright 2022 The Katalyst Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/kubewharf/katalyst-api/pkg/apis/config/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeStrategyGroupConfigurations implements StrategyGroupConfigurationInterface
type FakeStrategyGroupConfigurations struct {
	Fake *FakeConfigV1alpha1
}

var strategygroupconfigurationsResource = schema.GroupVersionResource{Group: "config.katalyst.kubewharf.io", Version: "v1alpha1", Resource: "strategygroupconfigurations"}

var strategygroupconfigurationsKind = schema.GroupVersionKind{Group: "config.katalyst.kubewharf.io", Version: "v1alpha1", Kind: "StrategyGroupConfiguration"}

// Get takes name of the strategyGroupConfiguration, and returns the corresponding strategyGroupConfiguration object, and an error if there is any.
func (c *FakeStrategyGroupConfigurations) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.StrategyGroupConfiguration, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(strategygroupconfigurationsResource, name), &v1alpha1.StrategyGroupConfiguration{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.StrategyGroupConfiguration), err
}

// List takes label and field selectors, and returns the list of StrategyGroupConfigurations that match those selectors.
func (c *FakeStrategyGroupConfigurations) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.StrategyGroupConfigurationList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(strategygroupconfigurationsResource, strategygroupconfigurationsKind, opts), &v1alpha1.StrategyGroupConfigurationList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.StrategyGroupConfigurationList{ListMeta: obj.(*v1alpha1.StrategyGroupConfigurationList).ListMeta}
	for _, item := range obj.(*v1alpha1.StrategyGroupConfigurationList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested strategyGroupConfigurations.
func (c *FakeStrategyGroupConfigurations) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(strategygroupconfigurationsResource, opts))
}

// Create takes the representation of a strategyGroupConfiguration and creates it.  Returns the server's representation of the strategyGroupConfiguration, and an error, if there is any.
func (c *FakeStrategyGroupConfigurations) Create(ctx context.Context, strategyGroupConfiguration *v1alpha1.StrategyGroupConfiguration, opts v1.CreateOptions) (result *v1alpha1.StrategyGroupConfiguration, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(strategygroupconfigurationsResource, strategyGroupConfiguration), &v1alpha1.StrategyGroupConfiguration{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.StrategyGroupConfiguration), err
}

// Update takes the representation of a strategyGroupConfiguration and updates it. Returns the server's representation of the strategyGroupConfiguration, and an error, if there is any.
func (c *FakeStrategyGroupConfigurations) Update(ctx context.Context, strategyGroupConfiguration *v1alpha1.StrategyGroupConfiguration, opts v1.UpdateOptions) (result *v1alpha1.StrategyGroupConfiguration, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(strategygroupconfigurationsResource, strategyGroupConfiguration), &v1alpha1.StrategyGroupConfiguration{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.StrategyGroupConfiguration), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeStrategyGroupConfigurations) UpdateStatus(ctx context.Context, strategyGroupConfiguration *v1alpha1.StrategyGroupConfiguration, opts v1.UpdateOptions) (*v1alpha1.StrategyGroupConfiguration, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(strategygroupconfigurationsResource, "status", strategyGroupConfiguration), &v1alpha1.StrategyGroupConfiguration{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.StrategyGroupConfiguration), err
}

// Delete takes name of the strategyGroupConfiguration and deletes it. Returns an error if one occurs.
func (c *FakeStrategyGroupConfigurations) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(strategygroupconfigurationsResource, name), &v1alpha1.StrategyGroupConfiguration{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeStrategyGroupConfigurations) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(strategygroupconfigurationsResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.StrategyGroupConfigurationList{})
	return err
}

// Patch applies the patch and returns the patched strategyGroupConfiguration.
func (c *FakeStrategyGroupConfigurations) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.StrategyGroupConfiguration, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(strategygroupconfigurationsResource, name, pt, data, subresources...), &v1alpha1.StrategyGroupConfiguration{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.StrategyGroupConfiguration), err
}
