/*
Copyright 2022 The Katalyst Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/kubewharf/katalyst-api/pkg/apis/config/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeStrategyGroups implements StrategyGroupInterface
type FakeStrategyGroups struct {
	Fake *FakeConfigV1alpha1
}

var strategygroupsResource = schema.GroupVersionResource{Group: "config.katalyst.kubewharf.io", Version: "v1alpha1", Resource: "strategygroups"}

var strategygroupsKind = schema.GroupVersionKind{Group: "config.katalyst.kubewharf.io", Version: "v1alpha1", Kind: "StrategyGroup"}

// Get takes name of the strategyGroup, and returns the corresponding strategyGroup object, and an error if there is any.
func (c *FakeStrategyGroups) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.StrategyGroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(strategygroupsResource, name), &v1alpha1.StrategyGroup{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.StrategyGroup), err
}

// List takes label and field selectors, and returns the list of StrategyGroups that match those selectors.
func (c *FakeStrategyGroups) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.StrategyGroupList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(strategygroupsResource, strategygroupsKind, opts), &v1alpha1.StrategyGroupList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.StrategyGroupList{ListMeta: obj.(*v1alpha1.StrategyGroupList).ListMeta}
	for _, item := range obj.(*v1alpha1.StrategyGroupList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested strategyGroups.
func (c *FakeStrategyGroups) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(strategygroupsResource, opts))
}

// Create takes the representation of a strategyGroup and creates it.  Returns the server's representation of the strategyGroup, and an error, if there is any.
func (c *FakeStrategyGroups) Create(ctx context.Context, strategyGroup *v1alpha1.StrategyGroup, opts v1.CreateOptions) (result *v1alpha1.StrategyGroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(strategygroupsResource, strategyGroup), &v1alpha1.StrategyGroup{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.StrategyGroup), err
}

// Update takes the representation of a strategyGroup and updates it. Returns the server's representation of the strategyGroup, and an error, if there is any.
func (c *FakeStrategyGroups) Update(ctx context.Context, strategyGroup *v1alpha1.StrategyGroup, opts v1.UpdateOptions) (result *v1alpha1.StrategyGroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(strategygroupsResource, strategyGroup), &v1alpha1.StrategyGroup{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.StrategyGroup), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeStrategyGroups) UpdateStatus(ctx context.Context, strategyGroup *v1alpha1.StrategyGroup, opts v1.UpdateOptions) (*v1alpha1.StrategyGroup, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(strategygroupsResource, "status", strategyGroup), &v1alpha1.StrategyGroup{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.StrategyGroup), err
}

// Delete takes name of the strategyGroup and deletes it. Returns an error if one occurs.
func (c *FakeStrategyGroups) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(strategygroupsResource, name, opts), &v1alpha1.StrategyGroup{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeStrategyGroups) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(strategygroupsResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.StrategyGroupList{})
	return err
}

// Patch applies the patch and returns the patched strategyGroup.
func (c *FakeStrategyGroups) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.StrategyGroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(strategygroupsResource, name, pt, data, subresources...), &v1alpha1.StrategyGroup{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.StrategyGroup), err
}
