/*
Copyright 2022 The Katalyst Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/kubewharf/katalyst-api/pkg/apis/config/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeHyperParameterConfigurations implements HyperParameterConfigurationInterface
type FakeHyperParameterConfigurations struct {
	Fake *FakeConfigV1alpha1
	ns   string
}

var hyperparameterconfigurationsResource = schema.GroupVersionResource{Group: "config.katalyst.kubewharf.io", Version: "v1alpha1", Resource: "hyperparameterconfigurations"}

var hyperparameterconfigurationsKind = schema.GroupVersionKind{Group: "config.katalyst.kubewharf.io", Version: "v1alpha1", Kind: "HyperParameterConfiguration"}

// Get takes name of the hyperParameterConfiguration, and returns the corresponding hyperParameterConfiguration object, and an error if there is any.
func (c *FakeHyperParameterConfigurations) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.HyperParameterConfiguration, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(hyperparameterconfigurationsResource, c.ns, name), &v1alpha1.HyperParameterConfiguration{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.HyperParameterConfiguration), err
}

// List takes label and field selectors, and returns the list of HyperParameterConfigurations that match those selectors.
func (c *FakeHyperParameterConfigurations) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.HyperParameterConfigurationList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(hyperparameterconfigurationsResource, hyperparameterconfigurationsKind, c.ns, opts), &v1alpha1.HyperParameterConfigurationList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.HyperParameterConfigurationList{ListMeta: obj.(*v1alpha1.HyperParameterConfigurationList).ListMeta}
	for _, item := range obj.(*v1alpha1.HyperParameterConfigurationList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested hyperParameterConfigurations.
func (c *FakeHyperParameterConfigurations) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(hyperparameterconfigurationsResource, c.ns, opts))

}

// Create takes the representation of a hyperParameterConfiguration and creates it.  Returns the server's representation of the hyperParameterConfiguration, and an error, if there is any.
func (c *FakeHyperParameterConfigurations) Create(ctx context.Context, hyperParameterConfiguration *v1alpha1.HyperParameterConfiguration, opts v1.CreateOptions) (result *v1alpha1.HyperParameterConfiguration, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(hyperparameterconfigurationsResource, c.ns, hyperParameterConfiguration), &v1alpha1.HyperParameterConfiguration{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.HyperParameterConfiguration), err
}

// Update takes the representation of a hyperParameterConfiguration and updates it. Returns the server's representation of the hyperParameterConfiguration, and an error, if there is any.
func (c *FakeHyperParameterConfigurations) Update(ctx context.Context, hyperParameterConfiguration *v1alpha1.HyperParameterConfiguration, opts v1.UpdateOptions) (result *v1alpha1.HyperParameterConfiguration, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(hyperparameterconfigurationsResource, c.ns, hyperParameterConfiguration), &v1alpha1.HyperParameterConfiguration{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.HyperParameterConfiguration), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeHyperParameterConfigurations) UpdateStatus(ctx context.Context, hyperParameterConfiguration *v1alpha1.HyperParameterConfiguration, opts v1.UpdateOptions) (*v1alpha1.HyperParameterConfiguration, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(hyperparameterconfigurationsResource, "status", c.ns, hyperParameterConfiguration), &v1alpha1.HyperParameterConfiguration{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.HyperParameterConfiguration), err
}

// Delete takes name of the hyperParameterConfiguration and deletes it. Returns an error if one occurs.
func (c *FakeHyperParameterConfigurations) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(hyperparameterconfigurationsResource, c.ns, name, opts), &v1alpha1.HyperParameterConfiguration{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeHyperParameterConfigurations) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(hyperparameterconfigurationsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.HyperParameterConfigurationList{})
	return err
}

// Patch applies the patch and returns the patched hyperParameterConfiguration.
func (c *FakeHyperParameterConfigurations) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.HyperParameterConfiguration, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(hyperparameterconfigurationsResource, c.ns, name, pt, data, subresources...), &v1alpha1.HyperParameterConfiguration{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.HyperParameterConfiguration), err
}
